# Code generated by liter-lm-e2e-generator. DO NOT EDIT.
defmodule LiterLmE2E.ErrorHandlingTest do
  use ExUnit.Case, async: true

  alias LiterLmE2E.MockServer
  alias LiterLmE2E.Helpers

  test "401 Unauthorized error when API key is invalid or missing" do
    routes = [
      %{
        path: "/chat/completions",
        method: "POST",
        status: 401,
        body:
          "{\\\"error\\\":{\\\"code\\\":\\\"invalid_api_key\\\",\\\"message\\\":\\\"Incorrect API key provided. You can find your API key at https://platform.openai.com/account/api-keys.\\\",\\\"param\\\":null,\\\"type\\\":\\\"invalid_request_error\\\"}}",
        stream_chunks: []
      }
    ]

    {:ok, base_url} = MockServer.start(routes)

    {:ok, resp} =
      Req.post(base_url <> "/chat/completions",
        body:
          "{\\\"messages\\\":[{\\\"content\\\":\\\"Hello\\\",\\\"role\\\":\\\"user\\\"}],\\\"model\\\":\\\"gpt-4\\\"}",
        headers: [{"content-type", "application/json"}]
      )

    assert resp.status == 401
  end

  test "429 Too Many Requests error when the rate limit is exceeded" do
    routes = [
      %{
        path: "/chat/completions",
        method: "POST",
        status: 429,
        body:
          "{\\\"error\\\":{\\\"code\\\":\\\"rate_limit_exceeded\\\",\\\"message\\\":\\\"Rate limit reached for gpt-4 in organization org-abc123 on tokens per min. Limit: 10000, Used: 10000, Requested: 100. Please try again in 600ms.\\\",\\\"param\\\":null,\\\"type\\\":\\\"requests\\\"}}",
        stream_chunks: []
      }
    ]

    {:ok, base_url} = MockServer.start(routes)

    {:ok, resp} =
      Req.post(base_url <> "/chat/completions",
        body:
          "{\\\"messages\\\":[{\\\"content\\\":\\\"Hello\\\",\\\"role\\\":\\\"user\\\"}],\\\"model\\\":\\\"gpt-4\\\"}",
        headers: [{"content-type", "application/json"}]
      )

    assert resp.status == 429
  end

  test "500 Internal Server Error from the upstream API" do
    routes = [
      %{
        path: "/chat/completions",
        method: "POST",
        status: 500,
        body:
          "{\\\"error\\\":{\\\"code\\\":null,\\\"message\\\":\\\"The server had an error while processing your request. Sorry about that!\\\",\\\"param\\\":null,\\\"type\\\":\\\"server_error\\\"}}",
        stream_chunks: []
      }
    ]

    {:ok, base_url} = MockServer.start(routes)

    {:ok, resp} =
      Req.post(base_url <> "/chat/completions",
        body:
          "{\\\"messages\\\":[{\\\"content\\\":\\\"Hello\\\",\\\"role\\\":\\\"user\\\"}],\\\"model\\\":\\\"gpt-4\\\"}",
        headers: [{"content-type", "application/json"}]
      )

    assert resp.status == 500
  end
end
