# Code generated by liter-lm-e2e-generator. DO NOT EDIT.
defmodule LiterLmE2E.StreamingTest do
  use ExUnit.Case, async: true

  alias LiterLmE2E.MockServer
  alias LiterLmE2E.Helpers

  test "Streaming chat completion that produces content across multiple SSE chunks" do
    routes = [
      %{
        path: "/chat/completions",
        method: "POST",
        status: 200,
        body: "null",
        stream_chunks: [
          "{\\\"choices\\\":[{\\\"delta\\\":{\\\"content\\\":\\\"\\\",\\\"role\\\":\\\"assistant\\\"},\\\"finish_reason\\\":null,\\\"index\\\":0}],\\\"created\\\":1711000000,\\\"id\\\":\\\"chatcmpl-stream001\\\",\\\"model\\\":\\\"gpt-4\\\",\\\"object\\\":\\\"chat.completion.chunk\\\"}",
          "{\\\"choices\\\":[{\\\"delta\\\":{\\\"content\\\":\\\"1\\\"},\\\"finish_reason\\\":null,\\\"index\\\":0}],\\\"created\\\":1711000000,\\\"id\\\":\\\"chatcmpl-stream001\\\",\\\"model\\\":\\\"gpt-4\\\",\\\"object\\\":\\\"chat.completion.chunk\\\"}",
          "{\\\"choices\\\":[{\\\"delta\\\":{\\\"content\\\":\\\" 2\\\"},\\\"finish_reason\\\":null,\\\"index\\\":0}],\\\"created\\\":1711000000,\\\"id\\\":\\\"chatcmpl-stream001\\\",\\\"model\\\":\\\"gpt-4\\\",\\\"object\\\":\\\"chat.completion.chunk\\\"}",
          "{\\\"choices\\\":[{\\\"delta\\\":{\\\"content\\\":\\\" 3\\\"},\\\"finish_reason\\\":null,\\\"index\\\":0}],\\\"created\\\":1711000000,\\\"id\\\":\\\"chatcmpl-stream001\\\",\\\"model\\\":\\\"gpt-4\\\",\\\"object\\\":\\\"chat.completion.chunk\\\"}",
          "{\\\"choices\\\":[{\\\"delta\\\":{},\\\"finish_reason\\\":\\\"stop\\\",\\\"index\\\":0}],\\\"created\\\":1711000000,\\\"id\\\":\\\"chatcmpl-stream001\\\",\\\"model\\\":\\\"gpt-4\\\",\\\"object\\\":\\\"chat.completion.chunk\\\"}"
        ]
      }
    ]

    {:ok, base_url} = MockServer.start(routes)

    {:ok, resp} =
      Req.post(base_url <> "/chat/completions",
        body:
          "{\\\"messages\\\":[{\\\"content\\\":\\\"Count to 3\\\",\\\"role\\\":\\\"user\\\"}],\\\"model\\\":\\\"gpt-4\\\",\\\"stream\\\":true}",
        headers: [{"content-type", "application/json"}],
        into: :self
      )

    assert resp.status == 200

    chunks = collect_sse_chunks(resp)
    assert length(chunks) >= 3, "Expected at least 3 chunk(s), got #{length(chunks)}"
  end

  test "Verify that the [DONE] sentinel signal properly terminates the stream" do
    routes = [
      %{
        path: "/chat/completions",
        method: "POST",
        status: 200,
        body: "null",
        stream_chunks: [
          "{\\\"choices\\\":[{\\\"delta\\\":{\\\"content\\\":\\\"\\\",\\\"role\\\":\\\"assistant\\\"},\\\"finish_reason\\\":null,\\\"index\\\":0}],\\\"created\\\":1711000001,\\\"id\\\":\\\"chatcmpl-done001\\\",\\\"model\\\":\\\"gpt-4\\\",\\\"object\\\":\\\"chat.completion.chunk\\\"}",
          "{\\\"choices\\\":[{\\\"delta\\\":{\\\"content\\\":\\\"Done\\\"},\\\"finish_reason\\\":null,\\\"index\\\":0}],\\\"created\\\":1711000001,\\\"id\\\":\\\"chatcmpl-done001\\\",\\\"model\\\":\\\"gpt-4\\\",\\\"object\\\":\\\"chat.completion.chunk\\\"}",
          "{\\\"choices\\\":[{\\\"delta\\\":{},\\\"finish_reason\\\":\\\"stop\\\",\\\"index\\\":0}],\\\"created\\\":1711000001,\\\"id\\\":\\\"chatcmpl-done001\\\",\\\"model\\\":\\\"gpt-4\\\",\\\"object\\\":\\\"chat.completion.chunk\\\"}"
        ]
      }
    ]

    {:ok, base_url} = MockServer.start(routes)

    {:ok, resp} =
      Req.post(base_url <> "/chat/completions",
        body:
          "{\\\"messages\\\":[{\\\"content\\\":\\\"Say done\\\",\\\"role\\\":\\\"user\\\"}],\\\"model\\\":\\\"gpt-4\\\",\\\"stream\\\":true}",
        headers: [{"content-type", "application/json"}],
        into: :self
      )

    assert resp.status == 200

    chunks = collect_sse_chunks(resp)
    assert length(chunks) >= 1, "Expected at least 1 chunk(s), got #{length(chunks)}"
  end
end
