<?php

declare(strict_types=1);

// Code generated by liter-lm-e2e-generator. DO NOT EDIT.

namespace LiterLmE2E;

use PHPUnit\Framework\TestCase;

require_once __DIR__ . '/Helpers.php';

final class ErrorHandlingTest extends TestCase
{
    /** 401 Unauthorized error when API key is invalid or missing */
    public function testAuth401(): void
    {
        $routes = [
            new MockRoute(
                path: '/chat/completions',
                method: 'POST',
                status: 401,
                body: '{"error":{"code":"invalid_api_key","message":"Incorrect API key provided. You can find your API key at https://platform.openai.com/account/api-keys.","param":null,"type":"invalid_request_error"}}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/chat/completions', 'POST', '{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}');
        $server->stop();

        $this->assertEquals(401, $result['status']);
    }

    /** 429 Too Many Requests error when the rate limit is exceeded */
    public function testRateLimit429(): void
    {
        $routes = [
            new MockRoute(
                path: '/chat/completions',
                method: 'POST',
                status: 429,
                body: '{"error":{"code":"rate_limit_exceeded","message":"Rate limit reached for gpt-4 in organization org-abc123 on tokens per min. Limit: 10000, Used: 10000, Requested: 100. Please try again in 600ms.","param":null,"type":"requests"}}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/chat/completions', 'POST', '{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}');
        $server->stop();

        $this->assertEquals(429, $result['status']);
    }

    /** 500 Internal Server Error from the upstream API */
    public function testServerError500(): void
    {
        $routes = [
            new MockRoute(
                path: '/chat/completions',
                method: 'POST',
                status: 500,
                body: '{"error":{"code":null,"message":"The server had an error while processing your request. Sorry about that!","param":null,"type":"server_error"}}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/chat/completions', 'POST', '{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}');
        $server->stop();

        $this->assertEquals(500, $result['status']);
    }
}
