<?php

declare(strict_types=1);

// Code generated by liter-lm-e2e-generator. DO NOT EDIT.

namespace LiterLmE2E;

use PHPUnit\Framework\TestCase;

require_once __DIR__ . '/Helpers.php';

final class SmokeTest extends TestCase
{
    /** Basic chat completion with a single user message */
    public function testBasicChat(): void
    {
        $routes = [
            new MockRoute(
                path: '/chat/completions',
                method: 'POST',
                status: 200,
                body: '{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hello!","role":"assistant"}}],"created":1711000000,"id":"chatcmpl-abc123","model":"gpt-4","object":"chat.completion","usage":{"completion_tokens":5,"prompt_tokens":10,"total_tokens":15}}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/chat/completions', 'POST', '{"messages":[{"content":"Say hello","role":"user"}],"model":"gpt-4","temperature":0}');
        $server->stop();

        $this->assertEquals(200, $result['status']);
        $doc = json_decode($result['body'], true, 512, JSON_THROW_ON_ERROR);

        $this->assertCount(1, $doc['choices']);
        $this->assertEquals('Hello!', $doc['choices'][0]['message']['content']);
        $this->assertEquals('stop', $doc['choices'][0]['finish_reason']);
        $this->assertEquals(15, $doc['usage']['total_tokens']);
        $this->assertEquals('gpt-4', $doc['model']);
    }

    /** Basic embedding request for a single input string */
    public function testBasicEmbed(): void
    {
        $routes = [
            new MockRoute(
                path: '/embeddings',
                method: 'POST',
                status: 200,
                body: '{"data":[{"embedding":[0.1,0.2,0.3,0.4,0.5],"index":0,"object":"embedding"}],"model":"text-embedding-3-small","object":"list","usage":{"completion_tokens":0,"prompt_tokens":2,"total_tokens":2}}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/embeddings', 'POST', '{"input":"Hello world","model":"text-embedding-3-small"}');
        $server->stop();

        $this->assertEquals(200, $result['status']);
        $doc = json_decode($result['body'], true, 512, JSON_THROW_ON_ERROR);

        $this->assertCount(1, $doc['data']);
    }

    /** List available models from the API */
    public function testBasicListModels(): void
    {
        $routes = [
            new MockRoute(
                path: '/models',
                method: 'GET',
                status: 200,
                body: '{"data":[{"created":1687882411,"id":"gpt-4","object":"model","owned_by":"openai"},{"created":1677610602,"id":"gpt-3.5-turbo","object":"model","owned_by":"openai"},{"created":1705948997,"id":"text-embedding-3-small","object":"model","owned_by":"openai"}],"object":"list"}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/models', 'GET');
        $server->stop();

        $this->assertEquals(200, $result['status']);
        $doc = json_decode($result['body'], true, 512, JSON_THROW_ON_ERROR);

        $this->assertCount(3, $doc['data']);
    }
}
