<?php

declare(strict_types=1);

// Code generated by liter-lm-e2e-generator. DO NOT EDIT.

namespace LiterLmE2E;

use PHPUnit\Framework\TestCase;

require_once __DIR__ . '/Helpers.php';

final class StreamingTest extends TestCase
{
    /** Streaming chat completion that produces content across multiple SSE chunks */
    public function testBasicStream(): void
    {
        $routes = [
            new MockRoute(
                path: '/chat/completions',
                method: 'POST',
                status: 200,
                body: 'null',
                streamChunks: [
                    '{"choices":[{"delta":{"content":"","role":"assistant"},"finish_reason":null,"index":0}],"created":1711000000,"id":"chatcmpl-stream001","model":"gpt-4","object":"chat.completion.chunk"}',
                    '{"choices":[{"delta":{"content":"1"},"finish_reason":null,"index":0}],"created":1711000000,"id":"chatcmpl-stream001","model":"gpt-4","object":"chat.completion.chunk"}',
                    '{"choices":[{"delta":{"content":" 2"},"finish_reason":null,"index":0}],"created":1711000000,"id":"chatcmpl-stream001","model":"gpt-4","object":"chat.completion.chunk"}',
                    '{"choices":[{"delta":{"content":" 3"},"finish_reason":null,"index":0}],"created":1711000000,"id":"chatcmpl-stream001","model":"gpt-4","object":"chat.completion.chunk"}',
                    '{"choices":[{"delta":{},"finish_reason":"stop","index":0}],"created":1711000000,"id":"chatcmpl-stream001","model":"gpt-4","object":"chat.completion.chunk"}',
                ],
            ),
        ];

        $server = new MockServer($routes);
        $chunks = readSseChunks($server->url . '/chat/completions', 'POST', '{"messages":[{"content":"Count to 3","role":"user"}],"model":"gpt-4","stream":true}');
        $server->stop();

        $this->assertGreaterThanOrEqual(3, count($chunks), 'Expected at least 3 chunk(s)');
    }

    /** Verify that the [DONE] sentinel signal properly terminates the stream */
    public function testStreamDoneSignal(): void
    {
        $routes = [
            new MockRoute(
                path: '/chat/completions',
                method: 'POST',
                status: 200,
                body: 'null',
                streamChunks: [
                    '{"choices":[{"delta":{"content":"","role":"assistant"},"finish_reason":null,"index":0}],"created":1711000001,"id":"chatcmpl-done001","model":"gpt-4","object":"chat.completion.chunk"}',
                    '{"choices":[{"delta":{"content":"Done"},"finish_reason":null,"index":0}],"created":1711000001,"id":"chatcmpl-done001","model":"gpt-4","object":"chat.completion.chunk"}',
                    '{"choices":[{"delta":{},"finish_reason":"stop","index":0}],"created":1711000001,"id":"chatcmpl-done001","model":"gpt-4","object":"chat.completion.chunk"}',
                ],
            ),
        ];

        $server = new MockServer($routes);
        $chunks = readSseChunks($server->url . '/chat/completions', 'POST', '{"messages":[{"content":"Say done","role":"user"}],"model":"gpt-4","stream":true}');
        $server->stop();

        $this->assertGreaterThanOrEqual(1, count($chunks), 'Expected at least 1 chunk(s)');
    }
}
