<?php

declare(strict_types=1);

// Code generated by liter-lm-e2e-generator. DO NOT EDIT.

namespace LiterLmE2E;

use PHPUnit\Framework\TestCase;

require_once __DIR__ . '/Helpers.php';

final class ToolCallingTest extends TestCase
{
    /** Chat request with a tool definition; assistant responds with a tool call */
    public function testSingleToolCall(): void
    {
        $routes = [
            new MockRoute(
                path: '/chat/completions',
                method: 'POST',
                status: 200,
                body: '{"choices":[{"finish_reason":"tool_calls","index":0,"message":{"content":null,"role":"assistant","tool_calls":[{"function":{"arguments":"{\\"location\\": \\"San Francisco, CA\\", \\"unit\\": \\"fahrenheit\\"}","name":"get_weather"},"id":"call_abc123","type":"function"}]}}],"created":1711000002,"id":"chatcmpl-tool001","model":"gpt-4","object":"chat.completion","usage":{"completion_tokens":17,"prompt_tokens":82,"total_tokens":99}}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/chat/completions', 'POST', '{"messages":[{"content":"What is the weather in San Francisco?","role":"user"}],"model":"gpt-4","tool_choice":"auto","tools":[{"function":{"description":"Get the current weather for a given location","name":"get_weather","parameters":{"properties":{"location":{"description":"The city and state, e.g. San Francisco, CA","type":"string"},"unit":{"description":"The temperature unit to use","enum":["celsius","fahrenheit"],"type":"string"}},"required":["location"],"type":"object"}},"type":"function"}]}');
        $server->stop();

        $this->assertEquals(200, $result['status']);
        $doc = json_decode($result['body'], true, 512, JSON_THROW_ON_ERROR);

        $this->assertCount(1, $doc['choices']);
        $this->assertEquals('tool_calls', $doc['choices'][0]['finish_reason']);
        $this->assertEquals(99, $doc['usage']['total_tokens']);
        $this->assertEquals('gpt-4', $doc['model']);
    }
}
