// Code generated by liter-lm-e2e-generator. DO NOT EDIT.
package dev.kreuzberg.literlm.e2e;

import static org.junit.jupiter.api.Assertions.*;

import java.net.http.HttpResponse;
import java.util.List;
import org.junit.jupiter.api.Test;

/** E2E tests for category: error-handling. */
class ErrorHandlingTest {

  /** 401 Unauthorized error when API key is invalid or missing */
  @Test
  void auth401() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/chat/completions",
                    "POST",
                    401,
                    "{\"error\":{\"code\":\"invalid_api_key\",\"message\":\"Incorrect API key"
                        + " provided. You can find your API key at"
                        + " https://platform.openai.com/account/api-keys.\",\"param\":null,\"type\":\"invalid_request_error\"}}")))) {

      HttpResponse<String> resp =
          Helpers.postJson(
              server.url,
              "/chat/completions",
              "{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}");

      assertEquals(401, resp.statusCode(), "error status code");
      assertTrue(resp.statusCode() >= 400, "expected error status");
    }
  }

  /** 429 Too Many Requests error when the rate limit is exceeded */
  @Test
  void rateLimit429() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/chat/completions",
                    "POST",
                    429,
                    "{\"error\":{\"code\":\"rate_limit_exceeded\",\"message\":\"Rate limit reached"
                        + " for gpt-4 in organization org-abc123 on tokens per min. Limit: 10000,"
                        + " Used: 10000, Requested: 100. Please try again in"
                        + " 600ms.\",\"param\":null,\"type\":\"requests\"}}")))) {

      HttpResponse<String> resp =
          Helpers.postJson(
              server.url,
              "/chat/completions",
              "{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}");

      assertEquals(429, resp.statusCode(), "error status code");
      assertTrue(resp.statusCode() >= 400, "expected error status");
    }
  }

  /** 500 Internal Server Error from the upstream API */
  @Test
  void serverError500() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/chat/completions",
                    "POST",
                    500,
                    "{\"error\":{\"code\":null,\"message\":\"The server had an error while"
                        + " processing your request. Sorry about"
                        + " that!\",\"param\":null,\"type\":\"server_error\"}}")))) {

      HttpResponse<String> resp =
          Helpers.postJson(
              server.url,
              "/chat/completions",
              "{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}");

      assertEquals(500, resp.statusCode(), "error status code");
      assertTrue(resp.statusCode() >= 400, "expected error status");
    }
  }
}
