// Code generated by liter-lm-e2e-generator. DO NOT EDIT.
package dev.kreuzberg.literlm.e2e;

import static org.junit.jupiter.api.Assertions.*;

import com.fasterxml.jackson.databind.JsonNode;
import java.net.http.HttpResponse;
import java.util.List;
import org.junit.jupiter.api.Test;

/** E2E tests for category: smoke. */
class SmokeTest {

  /** Basic chat completion with a single user message */
  @Test
  void basicChat() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/chat/completions",
                    "POST",
                    200,
                    "{\"choices\":[{\"finish_reason\":\"stop\",\"index\":0,\"message\":{\"content\":\"Hello!\",\"role\":\"assistant\"}}],\"created\":1711000000,\"id\":\"chatcmpl-abc123\",\"model\":\"gpt-4\",\"object\":\"chat.completion\",\"usage\":{\"completion_tokens\":5,\"prompt_tokens\":10,\"total_tokens\":15}}")))) {

      HttpResponse<String> resp =
          Helpers.postJson(
              server.url,
              "/chat/completions",
              "{\"messages\":[{\"content\":\"Say"
                  + " hello\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"temperature\":0}");

      assertEquals(200, resp.statusCode(), "HTTP status code");

      JsonNode body = Helpers.MAPPER.readTree(resp.body());

      assertEquals(1, body.get("choices").size(), "choices count");
      assertEquals(
          "Hello!", body.at("/choices/0/message/content").asText(), "first choice content");
      assertEquals("stop", body.at("/choices/0/finish_reason").asText(), "finish_reason");
      assertEquals("gpt-4", body.get("model").asText(), "model");
      assertNotNull(body.get("usage"), "usage object");
      assertEquals(15, body.at("/usage/total_tokens").asLong(), "total_tokens");
    }
  }

  /** Basic embedding request for a single input string */
  @Test
  void basicEmbed() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/embeddings",
                    "POST",
                    200,
                    "{\"data\":[{\"embedding\":[0.1,0.2,0.3,0.4,0.5],\"index\":0,\"object\":\"embedding\"}],\"model\":\"text-embedding-3-small\",\"object\":\"list\",\"usage\":{\"completion_tokens\":0,\"prompt_tokens\":2,\"total_tokens\":2}}")))) {

      HttpResponse<String> resp =
          Helpers.postJson(
              server.url,
              "/embeddings",
              "{\"input\":\"Hello world\",\"model\":\"text-embedding-3-small\"}");

      assertEquals(200, resp.statusCode(), "HTTP status code");

      JsonNode body = Helpers.MAPPER.readTree(resp.body());
      assertEquals(1, body.get("data").size(), "embedding count");
    }
  }

  /** List available models from the API */
  @Test
  void basicListModels() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/models",
                    "GET",
                    200,
                    "{\"data\":[{\"created\":1687882411,\"id\":\"gpt-4\",\"object\":\"model\",\"owned_by\":\"openai\"},{\"created\":1677610602,\"id\":\"gpt-3.5-turbo\",\"object\":\"model\",\"owned_by\":\"openai\"},{\"created\":1705948997,\"id\":\"text-embedding-3-small\",\"object\":\"model\",\"owned_by\":\"openai\"}],\"object\":\"list\"}")))) {

      HttpResponse<String> resp = Helpers.getJson(server.url, "/models");

      assertEquals(200, resp.statusCode(), "HTTP status code");

      JsonNode body = Helpers.MAPPER.readTree(resp.body());
      assertEquals(3, body.get("data").size(), "model count");
    }
  }
}
