// Code generated by liter-lm-e2e-generator. DO NOT EDIT.
package dev.kreuzberg.literlm.e2e;

import static org.junit.jupiter.api.Assertions.*;

import com.fasterxml.jackson.databind.JsonNode;
import java.net.http.HttpResponse;
import java.util.List;
import org.junit.jupiter.api.Test;

/** E2E tests for category: tool-calling. */
class ToolCallingTest {

  /** Chat request with a tool definition; assistant responds with a tool call */
  @Test
  void singleToolCall() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/chat/completions",
                    "POST",
                    200,
                    "{\"choices\":[{\"finish_reason\":\"tool_calls\",\"index\":0,\"message\":{\"content\":null,\"role\":\"assistant\",\"tool_calls\":[{\"function\":{\"arguments\":\"{\\\"location\\\":"
                        + " \\\"San Francisco, CA\\\", \\\"unit\\\":"
                        + " \\\"fahrenheit\\\"}\",\"name\":\"get_weather\"},\"id\":\"call_abc123\",\"type\":\"function\"}]}}],\"created\":1711000002,\"id\":\"chatcmpl-tool001\",\"model\":\"gpt-4\",\"object\":\"chat.completion\",\"usage\":{\"completion_tokens\":17,\"prompt_tokens\":82,\"total_tokens\":99}}")))) {

      HttpResponse<String> resp =
          Helpers.postJson(
              server.url,
              "/chat/completions",
              "{\"messages\":[{\"content\":\"What is the weather in San"
                  + " Francisco?\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"tool_choice\":\"auto\",\"tools\":[{\"function\":{\"description\":\"Get"
                  + " the current weather for a given"
                  + " location\",\"name\":\"get_weather\",\"parameters\":{\"properties\":{\"location\":{\"description\":\"The"
                  + " city and state, e.g. San Francisco,"
                  + " CA\",\"type\":\"string\"},\"unit\":{\"description\":\"The temperature unit to"
                  + " use\",\"enum\":[\"celsius\",\"fahrenheit\"],\"type\":\"string\"}},\"required\":[\"location\"],\"type\":\"object\"}},\"type\":\"function\"}]}");

      assertEquals(200, resp.statusCode(), "HTTP status code");

      JsonNode body = Helpers.MAPPER.readTree(resp.body());

      assertEquals(1, body.get("choices").size(), "choices count");
      assertEquals("tool_calls", body.at("/choices/0/finish_reason").asText(), "finish_reason");
      assertEquals("gpt-4", body.get("model").asText(), "model");
      assertNotNull(body.get("usage"), "usage object");
      assertEquals(99, body.at("/usage/total_tokens").asLong(), "total_tokens");
    }
  }
}
