// Code generated by liter-lm-e2e-generator. DO NOT EDIT.
import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { startMockServer, type MockServer, type MockRoute } from "./helpers";
// @ts-ignore – binding not yet implemented; tests compile and fail at runtime
import { LlmClient } from "liter-lm";

describe("error-handling", () => {
  // 401 Unauthorized error when API key is invalid or missing
  it("auth_401", async () => {
    const routes: MockRoute[] = [
      {
        path: "/chat/completions",
        method: "POST",
        status: 401,
        body: `{"error":{"code":"invalid_api_key","message":"Incorrect API key provided. You can find your API key at https://platform.openai.com/account/api-keys.","param":null,"type":"invalid_request_error"}}`,
        streamChunks: [],
      },
    ];

    const server = await startMockServer(routes);
    try {
      const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

      let threw = false;
      try {
        await client.chat(JSON.parse(`{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}`));
      } catch (e) {
        threw = true;
        expect((e as Error).message ?? "", "Expected auth error").toMatch(/auth|unauthorized|401/i);
      }
      expect(threw, "Expected client.chat to throw").toBe(true);
    } finally {
      server.close();
    }
  });

  // 429 Too Many Requests error when the rate limit is exceeded
  it("rate_limit_429", async () => {
    const routes: MockRoute[] = [
      {
        path: "/chat/completions",
        method: "POST",
        status: 429,
        body: `{"error":{"code":"rate_limit_exceeded","message":"Rate limit reached for gpt-4 in organization org-abc123 on tokens per min. Limit: 10000, Used: 10000, Requested: 100. Please try again in 600ms.","param":null,"type":"requests"}}`,
        streamChunks: [],
      },
    ];

    const server = await startMockServer(routes);
    try {
      const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

      let threw = false;
      try {
        await client.chat(JSON.parse(`{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}`));
      } catch (e) {
        threw = true;
        expect((e as Error).message ?? "", "Expected rate limit error").toMatch(/rate.?limit|429/i);
      }
      expect(threw, "Expected client.chat to throw").toBe(true);
    } finally {
      server.close();
    }
  });

  // 500 Internal Server Error from the upstream API
  it("server_error_500", async () => {
    const routes: MockRoute[] = [
      {
        path: "/chat/completions",
        method: "POST",
        status: 500,
        body: `{"error":{"code":null,"message":"The server had an error while processing your request. Sorry about that!","param":null,"type":"server_error"}}`,
        streamChunks: [],
      },
    ];

    const server = await startMockServer(routes);
    try {
      const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

      let threw = false;
      try {
        await client.chat(JSON.parse(`{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}`));
      } catch (e) {
        threw = true;
        expect((e as Error).message ?? "", "Expected server error").toMatch(/server.?error|internal|500/i);
      }
      expect(threw, "Expected client.chat to throw").toBe(true);
    } finally {
      server.close();
    }
  });

});
