// Code generated by liter-lm-e2e-generator. DO NOT EDIT.
import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { startMockServer, type MockServer, type MockRoute } from "./helpers";
// @ts-ignore – binding not yet implemented; tests compile and fail at runtime
import { LlmClient } from "liter-lm";

describe("smoke", () => {
  // Basic chat completion with a single user message
  it("basic_chat", async () => {
    const routes: MockRoute[] = [
      {
        path: "/chat/completions",
        method: "POST",
        status: 200,
        body: `{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hello!","role":"assistant"}}],"created":1711000000,"id":"chatcmpl-abc123","model":"gpt-4","object":"chat.completion","usage":{"completion_tokens":5,"prompt_tokens":10,"total_tokens":15}}`,
        streamChunks: [],
      },
    ];

    const server = await startMockServer(routes);
    try {
      const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

      const response = await client.chat(JSON.parse(`{"messages":[{"content":"Say hello","role":"user"}],"model":"gpt-4","temperature":0}`));

      expect(response.choices.length, "Choices count mismatch").toBe(1);
      expect(response.choices[0].finishReason, "finish_reason mismatch").toBe("stop");
      expect(response.choices[0].message.content, "message content mismatch").toBe("Hello!");
      expect(response.usage, "Expected usage object").toBeTruthy();
      expect(response.usage.totalTokens, "total_tokens mismatch").toBe(15);
      expect(response.model, "model mismatch").toBe("gpt-4");
    } finally {
      server.close();
    }
  });

  // Basic embedding request for a single input string
  it("basic_embed", async () => {
    const routes: MockRoute[] = [
      {
        path: "/embeddings",
        method: "POST",
        status: 200,
        body: `{"data":[{"embedding":[0.1,0.2,0.3,0.4,0.5],"index":0,"object":"embedding"}],"model":"text-embedding-3-small","object":"list","usage":{"completion_tokens":0,"prompt_tokens":2,"total_tokens":2}}`,
        streamChunks: [],
      },
    ];

    const server = await startMockServer(routes);
    try {
      const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

      const response = await client.embed(JSON.parse(`{"input":"Hello world","model":"text-embedding-3-small"}`));

      expect(response.data.length, "Embedding count mismatch").toBe(1);
      expect(response.data[0].embedding.length, "Embedding dimension mismatch").toBe(5);
    } finally {
      server.close();
    }
  });

  // List available models from the API
  it("basic_list_models", async () => {
    const routes: MockRoute[] = [
      {
        path: "/models",
        method: "GET",
        status: 200,
        body: `{"data":[{"created":1687882411,"id":"gpt-4","object":"model","owned_by":"openai"},{"created":1677610602,"id":"gpt-3.5-turbo","object":"model","owned_by":"openai"},{"created":1705948997,"id":"text-embedding-3-small","object":"model","owned_by":"openai"}],"object":"list"}`,
        streamChunks: [],
      },
    ];

    const server = await startMockServer(routes);
    try {
      const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

      const response = await client.listModels();

      expect(response.data.length, "Model count mismatch").toBe(3);
    } finally {
      server.close();
    }
  });

});
