// Code generated by liter-lm-e2e-generator. DO NOT EDIT.
import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { startMockServer, type MockServer, type MockRoute } from "./helpers";
// @ts-ignore – binding not yet implemented; tests compile and fail at runtime
import { LlmClient } from "liter-lm";

describe("streaming", () => {
  // Streaming chat completion that produces content across multiple SSE chunks
  it("basic_stream", async () => {
    const routes: MockRoute[] = [
      {
        path: "/chat/completions",
        method: "POST",
        status: 200,
        body: `null`,
        streamChunks: [
          `{"choices":[{"delta":{"content":"","role":"assistant"},"finish_reason":null,"index":0}],"created":1711000000,"id":"chatcmpl-stream001","model":"gpt-4","object":"chat.completion.chunk"}`,
          `{"choices":[{"delta":{"content":"1"},"finish_reason":null,"index":0}],"created":1711000000,"id":"chatcmpl-stream001","model":"gpt-4","object":"chat.completion.chunk"}`,
          `{"choices":[{"delta":{"content":" 2"},"finish_reason":null,"index":0}],"created":1711000000,"id":"chatcmpl-stream001","model":"gpt-4","object":"chat.completion.chunk"}`,
          `{"choices":[{"delta":{"content":" 3"},"finish_reason":null,"index":0}],"created":1711000000,"id":"chatcmpl-stream001","model":"gpt-4","object":"chat.completion.chunk"}`,
          `{"choices":[{"delta":{},"finish_reason":"stop","index":0}],"created":1711000000,"id":"chatcmpl-stream001","model":"gpt-4","object":"chat.completion.chunk"}`,
        ],
      },
    ];

    const server = await startMockServer(routes);
    try {
      const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

      const stream = await client.chatStream(JSON.parse(`{"messages":[{"content":"Count to 3","role":"user"}],"model":"gpt-4","stream":true}`));
      const chunks: unknown[] = [];
      for await (const chunk of stream) {
        chunks.push(chunk);
      }

      expect(chunks.length, "Expected at least 3 chunk(s)").toBeGreaterThanOrEqual(3);
      const content = chunks
        .flatMap((c: unknown) => (c as { choices?: { delta?: { content?: string } }[] }).choices ?? [])
        .map((ch: { delta?: { content?: string } }) => ch.delta?.content ?? "")
        .join("");
      expect(content, "Stream content mismatch").toBe("1 2 3");
    } finally {
      server.close();
    }
  });

  // Verify that the [DONE] sentinel signal properly terminates the stream
  it("stream_done_signal", async () => {
    const routes: MockRoute[] = [
      {
        path: "/chat/completions",
        method: "POST",
        status: 200,
        body: `null`,
        streamChunks: [
          `{"choices":[{"delta":{"content":"","role":"assistant"},"finish_reason":null,"index":0}],"created":1711000001,"id":"chatcmpl-done001","model":"gpt-4","object":"chat.completion.chunk"}`,
          `{"choices":[{"delta":{"content":"Done"},"finish_reason":null,"index":0}],"created":1711000001,"id":"chatcmpl-done001","model":"gpt-4","object":"chat.completion.chunk"}`,
          `{"choices":[{"delta":{},"finish_reason":"stop","index":0}],"created":1711000001,"id":"chatcmpl-done001","model":"gpt-4","object":"chat.completion.chunk"}`,
        ],
      },
    ];

    const server = await startMockServer(routes);
    try {
      const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

      const stream = await client.chatStream(JSON.parse(`{"messages":[{"content":"Say done","role":"user"}],"model":"gpt-4","stream":true}`));
      const chunks: unknown[] = [];
      for await (const chunk of stream) {
        chunks.push(chunk);
      }

      expect(chunks.length, "Expected at least 1 chunk(s)").toBeGreaterThanOrEqual(1);
      const content = chunks
        .flatMap((c: unknown) => (c as { choices?: { delta?: { content?: string } }[] }).choices ?? [])
        .map((ch: { delta?: { content?: string } }) => ch.delta?.content ?? "")
        .join("");
      expect(content, "Stream content mismatch").toBe("Done");
    } finally {
      server.close();
    }
  });

});
