// Code generated by liter-lm-e2e-generator. DO NOT EDIT.
import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { startMockServer, type MockServer, type MockRoute } from "./helpers";
// @ts-ignore – binding not yet implemented; tests compile and fail at runtime
import { LlmClient } from "liter-lm";

describe("tool-calling", () => {
  // Chat request with a tool definition; assistant responds with a tool call
  it("single_tool_call", async () => {
    const routes: MockRoute[] = [
      {
        path: "/chat/completions",
        method: "POST",
        status: 200,
        body: `{"choices":[{"finish_reason":"tool_calls","index":0,"message":{"content":null,"role":"assistant","tool_calls":[{"function":{"arguments":"{\\"location\\": \\"San Francisco, CA\\", \\"unit\\": \\"fahrenheit\\"}","name":"get_weather"},"id":"call_abc123","type":"function"}]}}],"created":1711000002,"id":"chatcmpl-tool001","model":"gpt-4","object":"chat.completion","usage":{"completion_tokens":17,"prompt_tokens":82,"total_tokens":99}}`,
        streamChunks: [],
      },
    ];

    const server = await startMockServer(routes);
    try {
      const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

      const response = await client.chat(JSON.parse(`{"messages":[{"content":"What is the weather in San Francisco?","role":"user"}],"model":"gpt-4","tool_choice":"auto","tools":[{"function":{"description":"Get the current weather for a given location","name":"get_weather","parameters":{"properties":{"location":{"description":"The city and state, e.g. San Francisco, CA","type":"string"},"unit":{"description":"The temperature unit to use","enum":["celsius","fahrenheit"],"type":"string"}},"required":["location"],"type":"object"}},"type":"function"}]}`));

      expect(response.choices.length, "Choices count mismatch").toBe(1);
      expect(response.choices[0].finishReason, "finish_reason mismatch").toBe("tool_calls");
      expect(Array.isArray(response.choices[0].message.toolCalls) && response.choices[0].message.toolCalls.length > 0, "Expected tool_calls").toBe(true);
      expect(response.choices[0].message.toolCalls[0].function.name, "tool call function name mismatch").toBe("get_weather");
      expect(response.usage, "Expected usage object").toBeTruthy();
      expect(response.usage.totalTokens, "total_tokens mismatch").toBe(99);
      expect(response.model, "model mismatch").toBe("gpt-4");
    } finally {
      server.close();
    }
  });

});
