# Code generated by liter-lm-e2e-generator. DO NOT EDIT.

from __future__ import annotations

import pytest

from conftest import MockRoute, MockServerInfo
from liter_lm import LlmClient  # noqa: E402


@pytest.mark.asyncio
@pytest.mark.parametrize("mock_server", [[
    MockRoute(
        "/chat/completions",
        "POST",
        200,
        stream_chunks=[
            "{\"choices\":[{\"delta\":{\"content\":\"\",\"role\":\"assistant\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000000,\"id\":\"chatcmpl-stream001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
            "{\"choices\":[{\"delta\":{\"content\":\"1\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000000,\"id\":\"chatcmpl-stream001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
            "{\"choices\":[{\"delta\":{\"content\":\" 2\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000000,\"id\":\"chatcmpl-stream001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
            "{\"choices\":[{\"delta\":{\"content\":\" 3\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000000,\"id\":\"chatcmpl-stream001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
            "{\"choices\":[{\"delta\":{},\"finish_reason\":\"stop\",\"index\":0}],\"created\":1711000000,\"id\":\"chatcmpl-stream001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
        ],
    ),
]], indirect=True)
async def test_basic_stream(mock_server: MockServerInfo) -> None:
    """Streaming chat completion that produces content across multiple SSE chunks"""
    import json
    client = LlmClient(api_key="test-key", base_url=mock_server.url, max_retries=0)
    request = json.loads("{\"messages\":[{\"content\":\"Count to 3\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"stream\":true}")
    chunks = []
    async for chunk in client.chat_stream(**request):
        chunks.append(chunk)
    assert len(chunks) >= 3, f"Expected at least 3 chunk(s), got {len(chunks)}"
    content = "".join(c.choices[0].delta.content or "" for c in chunks if c.choices)
    assert content == "1 2 3", f"Stream content mismatch: {content!r}"


@pytest.mark.asyncio
@pytest.mark.parametrize("mock_server", [[
    MockRoute(
        "/chat/completions",
        "POST",
        200,
        stream_chunks=[
            "{\"choices\":[{\"delta\":{\"content\":\"\",\"role\":\"assistant\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000001,\"id\":\"chatcmpl-done001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
            "{\"choices\":[{\"delta\":{\"content\":\"Done\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000001,\"id\":\"chatcmpl-done001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
            "{\"choices\":[{\"delta\":{},\"finish_reason\":\"stop\",\"index\":0}],\"created\":1711000001,\"id\":\"chatcmpl-done001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
        ],
    ),
]], indirect=True)
async def test_stream_done_signal(mock_server: MockServerInfo) -> None:
    """Verify that the [DONE] sentinel signal properly terminates the stream"""
    import json
    client = LlmClient(api_key="test-key", base_url=mock_server.url, max_retries=0)
    request = json.loads("{\"messages\":[{\"content\":\"Say done\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"stream\":true}")
    chunks = []
    async for chunk in client.chat_stream(**request):
        chunks.append(chunk)
    assert len(chunks) >= 1, f"Expected at least 1 chunk(s), got {len(chunks)}"
    content = "".join(c.choices[0].delta.content or "" for c in chunks if c.choices)
    assert content == "Done", f"Stream content mismatch: {content!r}"
