# Code generated by liter-lm-e2e-generator. DO NOT EDIT.

from __future__ import annotations

import pytest

from conftest import MockRoute, MockServerInfo
from liter_lm import (  # noqa: E402
    LlmClient,
    AuthenticationError,
    RateLimitedError,
    ServerError,
    NotFoundError,
    ServiceUnavailableError,
    BadRequestError,
)


@pytest.mark.asyncio
@pytest.mark.parametrize("mock_server", [[
    MockRoute("/chat/completions", "POST", 401, "{\"error\":{\"code\":\"invalid_api_key\",\"message\":\"Incorrect API key provided. You can find your API key at https://platform.openai.com/account/api-keys.\",\"param\":null,\"type\":\"invalid_request_error\"}}"),
]], indirect=True)
async def test_auth_401(mock_server: MockServerInfo) -> None:
    """401 Unauthorized error when API key is invalid or missing"""
    import json
    client = LlmClient(api_key="test-key", base_url=mock_server.url, max_retries=0)
    request = json.loads("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
    with pytest.raises(AuthenticationError):
        await client.chat(**request)


@pytest.mark.asyncio
@pytest.mark.parametrize("mock_server", [[
    MockRoute("/chat/completions", "POST", 429, "{\"error\":{\"code\":\"rate_limit_exceeded\",\"message\":\"Rate limit reached for gpt-4 in organization org-abc123 on tokens per min. Limit: 10000, Used: 10000, Requested: 100. Please try again in 600ms.\",\"param\":null,\"type\":\"requests\"}}"),
]], indirect=True)
async def test_rate_limit_429(mock_server: MockServerInfo) -> None:
    """429 Too Many Requests error when the rate limit is exceeded"""
    import json
    client = LlmClient(api_key="test-key", base_url=mock_server.url, max_retries=0)
    request = json.loads("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
    with pytest.raises(RateLimitedError):
        await client.chat(**request)


@pytest.mark.asyncio
@pytest.mark.parametrize("mock_server", [[
    MockRoute("/chat/completions", "POST", 500, "{\"error\":{\"code\":null,\"message\":\"The server had an error while processing your request. Sorry about that!\",\"param\":null,\"type\":\"server_error\"}}"),
]], indirect=True)
async def test_server_error_500(mock_server: MockServerInfo) -> None:
    """500 Internal Server Error from the upstream API"""
    import json
    client = LlmClient(api_key="test-key", base_url=mock_server.url, max_retries=0)
    request = json.loads("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
    with pytest.raises(ServerError):
        await client.chat(**request)
