/* Auto-generated C bindings for liter-lm */

#ifndef LITER_LM_FFI_H
#define LITER_LM_FFI_H

#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#define LITER_LM_VERSION_MAJOR 1
#define LITER_LM_VERSION_MINOR 0
#define LITER_LM_VERSION_PATCH 0
#define LITER_LM_VERSION "1.0.0-rc.1"

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
/* Symbol visibility */
#ifndef LITER_LM_EXPORT
#if defined(LITER_LM_STATIC)
#define LITER_LM_EXPORT
#elif defined(_WIN32) || defined(__CYGWIN__)
#ifdef LITER_LM_BUILDING
#define LITER_LM_EXPORT __declspec(dllexport)
#else
#define LITER_LM_EXPORT __declspec(dllimport)
#endif
#elif defined(__GNUC__) || defined(__clang__)
#define LITER_LM_EXPORT __attribute__((visibility("default")))
#else
#define LITER_LM_EXPORT
#endif
#endif

/* Compiler attribute helpers
 *
 * LITER_LM_WARN_UNUSED  — caller must not discard the return value (e.g. an
 *                         allocated pointer or an error code).
 * LITER_LM_NONNULL(...) — the listed 1-based argument positions must never be
 *                         NULL.  Callers that pass NULL trigger UB; annotating
 *                         this lets GCC/Clang warn at compile time.
 */
#if defined(__GNUC__) || defined(__clang__)
#define LITER_LM_WARN_UNUSED __attribute__((warn_unused_result))
#define LITER_LM_NONNULL(...) __attribute__((nonnull(__VA_ARGS__)))
#else
#define LITER_LM_WARN_UNUSED
#define LITER_LM_NONNULL(...)
#endif

/**
 * Opaque handle to a liter-lm client.
 * Create with literlm_client_new(), free with literlm_client_free().
 */
typedef struct LiterLmClient LiterLmClient;

/**
 * Callback invoked for each SSE chunk during a streaming chat completion.
 *
 * - `chunk_json`: NUL-terminated JSON string for one `ChatCompletionChunk`.
 *   The pointer is valid only for the duration of the callback invocation.
 *   The callee must **not** free it.
 * - `user_data`: The opaque pointer passed to [`literlm_chat_stream`].
 *
 * This callback returns void; there is no return value.
 */
typedef void (*LiterLmStreamCallback)(const char *chunk_json, void *user_data);

/**
 * Create a new liter-lm client.
 *
 * # Parameters
 *
 * - `api_key`: NUL-terminated API key string.  Pass an empty string (`""`)
 *   when using a provider that does not require authentication.
 * - `base_url`: NUL-terminated base URL override.  Pass `NULL` to use the
 *   default provider routing based on model-name prefix.
 * - `model_hint`: NUL-terminated model name hint for provider auto-detection
 *   (e.g. `"groq/llama3-70b"`).  Pass `NULL` to default to OpenAI.  Used
 *   only when `base_url` is also `NULL`.
 *
 * # Return value
 *
 * Returns a heap-allocated `LiterLmClient*` on success, or `NULL` on failure.
 * Check [`literlm_last_error`] for the error message when `NULL` is returned.
 *
 * The returned pointer must be freed with [`literlm_client_free`].
 *
 * # Safety
 *
 * - `api_key` must be a valid, non-null, NUL-terminated C string.
 * - `base_url` may be `NULL` (treated as no override) or a valid NUL-terminated C string.
 * - `model_hint` may be `NULL` (treated as no hint) or a valid NUL-terminated C string.
 * - The caller owns the returned pointer and must call `literlm_client_free` exactly once.
 */
LITER_LM_EXPORT
LiterLmClient *literlm_client_new(const char *api_key, const char *base_url,
                                  const char *model_hint);

/**
 * Free a client created by [`literlm_client_new`].
 *
 * # Safety
 *
 * - `client` must be a valid pointer returned by `literlm_client_new`.
 * - `client` must not be used after this call (use-after-free is UB).
 * - Passing `NULL` is safe and is a no-op.
 */
LITER_LM_EXPORT void literlm_client_free(LiterLmClient *client);

/**
 * Send a chat completion request.
 *
 * # Parameters
 *
 * - `client`: A valid client pointer.
 * - `request_json`: NUL-terminated JSON string conforming to the
 *   `ChatCompletionRequest` schema.
 *
 * # Return value
 *
 * Returns a heap-allocated NUL-terminated JSON string containing the
 * `ChatCompletionResponse` on success, or `NULL` on failure.
 * Check [`literlm_last_error`] on failure.
 *
 * The caller must free the returned string with [`literlm_free_string`].
 *
 * # Safety
 *
 * - `client` must be a valid, non-null pointer returned by `literlm_client_new`.
 * - `request_json` must be a valid, non-null, NUL-terminated UTF-8 JSON string.
 */
LITER_LM_EXPORT char *literlm_chat(const LiterLmClient *client, const char *request_json);

/**
 * Send a streaming chat completion request, invoking a callback for each chunk.
 *
 * # Parameters
 *
 * - `client`: A valid client pointer.
 * - `request_json`: NUL-terminated JSON string conforming to the
 *   `ChatCompletionRequest` schema.
 * - `callback`: Function called once per SSE chunk with the JSON-serialised
 *   `ChatCompletionChunk`.  The `chunk_json` pointer is valid only for the
 *   duration of each callback invocation and must **not** be freed.
 * - `user_data`: Opaque pointer forwarded unchanged to each `callback` call.
 *   May be `NULL`.
 *
 * # Return value
 *
 * Returns `0` on success (all chunks delivered) or `-1` on failure.
 * Check [`literlm_last_error`] on failure.
 *
 * # Safety
 *
 * - `client` must be a valid, non-null pointer returned by `literlm_client_new`.
 * - `request_json` must be a valid, non-null, NUL-terminated UTF-8 JSON string.
 * - `callback` must be a valid function pointer; it is invoked from the calling
 *   thread with the Tokio runtime blocked.
 * - `user_data` is forwarded as-is; the caller is responsible for its lifetime.
 */
LITER_LM_EXPORT
int32_t literlm_chat_stream(const LiterLmClient *client, const char *request_json,
                            LiterLmStreamCallback callback, void *user_data);

/**
 * Send an embedding request.
 *
 * # Parameters
 *
 * - `client`: A valid client pointer.
 * - `request_json`: NUL-terminated JSON string conforming to the
 *   `EmbeddingRequest` schema.
 *
 * # Return value
 *
 * Returns a heap-allocated NUL-terminated JSON string containing the
 * `EmbeddingResponse` on success, or `NULL` on failure.
 * Check [`literlm_last_error`] on failure.
 *
 * The caller must free the returned string with [`literlm_free_string`].
 *
 * # Safety
 *
 * - `client` must be a valid, non-null pointer returned by `literlm_client_new`.
 * - `request_json` must be a valid, non-null, NUL-terminated UTF-8 JSON string.
 */
LITER_LM_EXPORT char *literlm_embed(const LiterLmClient *client, const char *request_json);

/**
 * List available models.
 *
 * # Parameters
 *
 * - `client`: A valid client pointer.
 *
 * # Return value
 *
 * Returns a heap-allocated NUL-terminated JSON string containing the
 * `ModelsListResponse` on success, or `NULL` on failure.
 * Check [`literlm_last_error`] on failure.
 *
 * The caller must free the returned string with [`literlm_free_string`].
 *
 * # Safety
 *
 * - `client` must be a valid, non-null pointer returned by `literlm_client_new`.
 */
LITER_LM_EXPORT char *literlm_list_models(const LiterLmClient *client);

/**
 * Generate an image from a text prompt.
 *
 * # Parameters
 *
 * - `client`: A valid client pointer.
 * - `request_json`: NUL-terminated JSON string conforming to the
 *   `CreateImageRequest` schema.
 *
 * # Return value
 *
 * Returns a heap-allocated NUL-terminated JSON string containing the
 * `ImagesResponse` on success, or `NULL` on failure.
 * The caller must free the returned string with [`literlm_free_string`].
 *
 * # Safety
 *
 * - `client` must be a valid, non-null pointer returned by `literlm_client_new`.
 * - `request_json` must be a valid, non-null, NUL-terminated UTF-8 JSON string.
 */
LITER_LM_EXPORT char *literlm_image_generate(const LiterLmClient *client, const char *request_json);

/**
 * Generate speech audio from text.
 *
 * # Parameters
 *
 * - `client`: A valid client pointer.
 * - `request_json`: NUL-terminated JSON string conforming to the
 *   `CreateSpeechRequest` schema.
 *
 * # Return value
 *
 * Returns a heap-allocated NUL-terminated base64-encoded string of the audio
 * bytes on success, or `NULL` on failure.
 * The caller must free the returned string with [`literlm_free_string`].
 *
 * # Safety
 *
 * - `client` must be a valid, non-null pointer returned by `literlm_client_new`.
 * - `request_json` must be a valid, non-null, NUL-terminated UTF-8 JSON string.
 */
LITER_LM_EXPORT char *literlm_speech(const LiterLmClient *client, const char *request_json);

/**
 * Transcribe audio to text.
 *
 * # Parameters
 *
 * - `client`: A valid client pointer.
 * - `request_json`: NUL-terminated JSON string conforming to the
 *   `CreateTranscriptionRequest` schema.
 *
 * # Return value
 *
 * Returns a heap-allocated NUL-terminated JSON string containing the
 * `TranscriptionResponse` on success, or `NULL` on failure.
 * The caller must free the returned string with [`literlm_free_string`].
 *
 * # Safety
 *
 * - `client` must be a valid, non-null pointer returned by `literlm_client_new`.
 * - `request_json` must be a valid, non-null, NUL-terminated UTF-8 JSON string.
 */
LITER_LM_EXPORT char *literlm_transcribe(const LiterLmClient *client, const char *request_json);

/**
 * Check content against moderation policies.
 *
 * # Parameters
 *
 * - `client`: A valid client pointer.
 * - `request_json`: NUL-terminated JSON string conforming to the
 *   `ModerationRequest` schema.
 *
 * # Return value
 *
 * Returns a heap-allocated NUL-terminated JSON string containing the
 * `ModerationResponse` on success, or `NULL` on failure.
 * The caller must free the returned string with [`literlm_free_string`].
 *
 * # Safety
 *
 * - `client` must be a valid, non-null pointer returned by `literlm_client_new`.
 * - `request_json` must be a valid, non-null, NUL-terminated UTF-8 JSON string.
 */
LITER_LM_EXPORT char *literlm_moderate(const LiterLmClient *client, const char *request_json);

/**
 * Rerank documents by relevance to a query.
 *
 * # Parameters
 *
 * - `client`: A valid client pointer.
 * - `request_json`: NUL-terminated JSON string conforming to the
 *   `RerankRequest` schema.
 *
 * # Return value
 *
 * Returns a heap-allocated NUL-terminated JSON string containing the
 * `RerankResponse` on success, or `NULL` on failure.
 * The caller must free the returned string with [`literlm_free_string`].
 *
 * # Safety
 *
 * - `client` must be a valid, non-null pointer returned by `literlm_client_new`.
 * - `request_json` must be a valid, non-null, NUL-terminated UTF-8 JSON string.
 */
LITER_LM_EXPORT char *literlm_rerank(const LiterLmClient *client, const char *request_json);

/**
 * Upload a file.
 *
 * # Parameters
 *
 * - `client`: A valid client pointer.
 * - `request_json`: NUL-terminated JSON string conforming to the
 *   `CreateFileRequest` schema.  The `file` field must be base64-encoded.
 *
 * # Return value
 *
 * Returns a heap-allocated NUL-terminated JSON string containing the
 * `FileObject` on success, or `NULL` on failure.
 * The caller must free the returned string with [`literlm_free_string`].
 *
 * # Safety
 *
 * - `client` must be a valid, non-null pointer returned by `literlm_client_new`.
 * - `request_json` must be a valid, non-null, NUL-terminated UTF-8 JSON string.
 */
LITER_LM_EXPORT char *literlm_create_file(const LiterLmClient *client, const char *request_json);

/**
 * Retrieve metadata for a file by ID.
 *
 * # Parameters
 *
 * - `client`: A valid client pointer.
 * - `file_id`: NUL-terminated file ID string.
 *
 * # Return value
 *
 * Returns a heap-allocated NUL-terminated JSON string containing the
 * `FileObject` on success, or `NULL` on failure.
 * The caller must free the returned string with [`literlm_free_string`].
 *
 * # Safety
 *
 * - `client` must be a valid, non-null pointer returned by `literlm_client_new`.
 * - `file_id` must be a valid, non-null, NUL-terminated UTF-8 string.
 */
LITER_LM_EXPORT char *literlm_retrieve_file(const LiterLmClient *client, const char *file_id);

/**
 * Delete a file by ID.
 *
 * # Parameters
 *
 * - `client`: A valid client pointer.
 * - `file_id`: NUL-terminated file ID string.
 *
 * # Return value
 *
 * Returns a heap-allocated NUL-terminated JSON string containing the
 * `DeleteResponse` on success, or `NULL` on failure.
 * The caller must free the returned string with [`literlm_free_string`].
 *
 * # Safety
 *
 * - `client` must be a valid, non-null pointer returned by `literlm_client_new`.
 * - `file_id` must be a valid, non-null, NUL-terminated UTF-8 string.
 */
LITER_LM_EXPORT char *literlm_delete_file(const LiterLmClient *client, const char *file_id);

/**
 * List files, optionally filtered by query parameters.
 *
 * # Parameters
 *
 * - `client`: A valid client pointer.
 * - `query_json`: NUL-terminated JSON string conforming to the
 *   `FileListQuery` schema.  May be `NULL` to list all files.
 *
 * # Return value
 *
 * Returns a heap-allocated NUL-terminated JSON string containing the
 * `FileListResponse` on success, or `NULL` on failure.
 * The caller must free the returned string with [`literlm_free_string`].
 *
 * # Safety
 *
 * - `client` must be a valid, non-null pointer returned by `literlm_client_new`.
 * - `query_json` may be `NULL` or a valid NUL-terminated UTF-8 JSON string.
 */
LITER_LM_EXPORT char *literlm_list_files(const LiterLmClient *client, const char *query_json);

/**
 * Retrieve the raw content of a file (returned as base64-encoded string).
 *
 * # Parameters
 *
 * - `client`: A valid client pointer.
 * - `file_id`: NUL-terminated file ID string.
 *
 * # Return value
 *
 * Returns a heap-allocated NUL-terminated base64-encoded string of the file
 * content on success, or `NULL` on failure.
 * The caller must free the returned string with [`literlm_free_string`].
 *
 * # Safety
 *
 * - `client` must be a valid, non-null pointer returned by `literlm_client_new`.
 * - `file_id` must be a valid, non-null, NUL-terminated UTF-8 string.
 */
LITER_LM_EXPORT char *literlm_file_content(const LiterLmClient *client, const char *file_id);

/**
 * Create a new batch job.
 *
 * # Parameters
 *
 * - `client`: A valid client pointer.
 * - `request_json`: NUL-terminated JSON string conforming to the
 *   `CreateBatchRequest` schema.
 *
 * # Return value
 *
 * Returns a heap-allocated NUL-terminated JSON string containing the
 * `BatchObject` on success, or `NULL` on failure.
 * The caller must free the returned string with [`literlm_free_string`].
 *
 * # Safety
 *
 * - `client` must be a valid, non-null pointer returned by `literlm_client_new`.
 * - `request_json` must be a valid, non-null, NUL-terminated UTF-8 JSON string.
 */
LITER_LM_EXPORT char *literlm_create_batch(const LiterLmClient *client, const char *request_json);

/**
 * Retrieve a batch by ID.
 *
 * # Parameters
 *
 * - `client`: A valid client pointer.
 * - `batch_id`: NUL-terminated batch ID string.
 *
 * # Return value
 *
 * Returns a heap-allocated NUL-terminated JSON string containing the
 * `BatchObject` on success, or `NULL` on failure.
 * The caller must free the returned string with [`literlm_free_string`].
 *
 * # Safety
 *
 * - `client` must be a valid, non-null pointer returned by `literlm_client_new`.
 * - `batch_id` must be a valid, non-null, NUL-terminated UTF-8 string.
 */
LITER_LM_EXPORT char *literlm_retrieve_batch(const LiterLmClient *client, const char *batch_id);

/**
 * List batches, optionally filtered by query parameters.
 *
 * # Parameters
 *
 * - `client`: A valid client pointer.
 * - `query_json`: NUL-terminated JSON string conforming to the
 *   `BatchListQuery` schema.  May be `NULL` to list all batches.
 *
 * # Return value
 *
 * Returns a heap-allocated NUL-terminated JSON string containing the
 * `BatchListResponse` on success, or `NULL` on failure.
 * The caller must free the returned string with [`literlm_free_string`].
 *
 * # Safety
 *
 * - `client` must be a valid, non-null pointer returned by `literlm_client_new`.
 * - `query_json` may be `NULL` or a valid NUL-terminated UTF-8 JSON string.
 */
LITER_LM_EXPORT char *literlm_list_batches(const LiterLmClient *client, const char *query_json);

/**
 * Cancel an in-progress batch.
 *
 * # Parameters
 *
 * - `client`: A valid client pointer.
 * - `batch_id`: NUL-terminated batch ID string.
 *
 * # Return value
 *
 * Returns a heap-allocated NUL-terminated JSON string containing the
 * `BatchObject` on success, or `NULL` on failure.
 * The caller must free the returned string with [`literlm_free_string`].
 *
 * # Safety
 *
 * - `client` must be a valid, non-null pointer returned by `literlm_client_new`.
 * - `batch_id` must be a valid, non-null, NUL-terminated UTF-8 string.
 */
LITER_LM_EXPORT char *literlm_cancel_batch(const LiterLmClient *client, const char *batch_id);

/**
 * Create a new response.
 *
 * # Parameters
 *
 * - `client`: A valid client pointer.
 * - `request_json`: NUL-terminated JSON string conforming to the
 *   `CreateResponseRequest` schema.
 *
 * # Return value
 *
 * Returns a heap-allocated NUL-terminated JSON string containing the
 * `ResponseObject` on success, or `NULL` on failure.
 * The caller must free the returned string with [`literlm_free_string`].
 *
 * # Safety
 *
 * - `client` must be a valid, non-null pointer returned by `literlm_client_new`.
 * - `request_json` must be a valid, non-null, NUL-terminated UTF-8 JSON string.
 */
LITER_LM_EXPORT
char *literlm_create_response(const LiterLmClient *client, const char *request_json);

/**
 * Retrieve a response by ID.
 *
 * # Parameters
 *
 * - `client`: A valid client pointer.
 * - `response_id`: NUL-terminated response ID string.
 *
 * # Return value
 *
 * Returns a heap-allocated NUL-terminated JSON string containing the
 * `ResponseObject` on success, or `NULL` on failure.
 * The caller must free the returned string with [`literlm_free_string`].
 *
 * # Safety
 *
 * - `client` must be a valid, non-null pointer returned by `literlm_client_new`.
 * - `response_id` must be a valid, non-null, NUL-terminated UTF-8 string.
 */
LITER_LM_EXPORT
char *literlm_retrieve_response(const LiterLmClient *client, const char *response_id);

/**
 * Cancel an in-progress response.
 *
 * # Parameters
 *
 * - `client`: A valid client pointer.
 * - `response_id`: NUL-terminated response ID string.
 *
 * # Return value
 *
 * Returns a heap-allocated NUL-terminated JSON string containing the
 * `ResponseObject` on success, or `NULL` on failure.
 * The caller must free the returned string with [`literlm_free_string`].
 *
 * # Safety
 *
 * - `client` must be a valid, non-null pointer returned by `literlm_client_new`.
 * - `response_id` must be a valid, non-null, NUL-terminated UTF-8 string.
 */
LITER_LM_EXPORT char *literlm_cancel_response(const LiterLmClient *client, const char *response_id);

/**
 * Retrieve the last error message for the current thread.
 *
 * Returns a `const char*` pointer to the NUL-terminated error string, or
 * `NULL` if no error has occurred since the last successful call.
 *
 * The returned pointer is valid only until the **next** liter-lm function
 * call on the **same thread**.  The caller must **not** free this pointer.
 *
 * # Safety
 *
 * Always safe to call.  No preconditions.
 */
LITER_LM_EXPORT const char *literlm_last_error(void);

/**
 * Free a string returned by [`literlm_chat`], [`literlm_embed`], or
 * [`literlm_list_models`].
 *
 * # Safety
 *
 * - `s` must be a pointer returned by one of the functions listed above.
 * - `s` must not be used after this call (use-after-free is UB).
 * - Passing `NULL` is safe and is a no-op.
 * - Do **not** pass the pointer returned by [`literlm_last_error`]; that
 *   pointer must not be freed.
 */
LITER_LM_EXPORT void literlm_free_string(char *s);

/**
 * Returns the version string of the liter-lm library.
 *
 * The returned pointer is valid for the lifetime of the program and must
 * **not** be freed.
 *
 * # Safety
 *
 * Always safe to call.
 */
LITER_LM_EXPORT const char *literlm_version(void);

#endif /* LITER_LM_FFI_H */
