// Code generated by liter-lm-e2e-generator. DO NOT EDIT.

using System.Text.Json;
using System.Net.Http;
using Xunit;

namespace LiterLmE2E;

public sealed class ErrorHandlingTests
{

    /// <summary>401 Unauthorized error when API key is invalid or missing</summary>
    [Fact]
    public async Task Auth401()
    {
        var routes = new[]
        {
            new MockRoute(
                Path: "/chat/completions",
                Method: "POST",
                Status: 401,
                Body: "{\"error\":{\"code\":\"invalid_api_key\",\"message\":\"Incorrect API key provided. You can find your API key at https://platform.openai.com/account/api-keys.\",\"param\":null,\"type\":\"invalid_request_error\"}}",
                StreamChunks: Array.Empty<string>()
            ),
        };

        using var server = new MockServer(routes);
        using var http = new HttpClient();
        http.BaseAddress = new Uri(server.Url);

        var content = new StringContent("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}", System.Text.Encoding.UTF8, "application/json");
        var response = await http.PostAsync("/chat/completions", content);
        Assert.Equal(401, (int)response.StatusCode);
    }

    /// <summary>429 Too Many Requests error when the rate limit is exceeded</summary>
    [Fact]
    public async Task RateLimit429()
    {
        var routes = new[]
        {
            new MockRoute(
                Path: "/chat/completions",
                Method: "POST",
                Status: 429,
                Body: "{\"error\":{\"code\":\"rate_limit_exceeded\",\"message\":\"Rate limit reached for gpt-4 in organization org-abc123 on tokens per min. Limit: 10000, Used: 10000, Requested: 100. Please try again in 600ms.\",\"param\":null,\"type\":\"requests\"}}",
                StreamChunks: Array.Empty<string>()
            ),
        };

        using var server = new MockServer(routes);
        using var http = new HttpClient();
        http.BaseAddress = new Uri(server.Url);

        var content = new StringContent("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}", System.Text.Encoding.UTF8, "application/json");
        var response = await http.PostAsync("/chat/completions", content);
        Assert.Equal(429, (int)response.StatusCode);
    }

    /// <summary>500 Internal Server Error from the upstream API</summary>
    [Fact]
    public async Task ServerError500()
    {
        var routes = new[]
        {
            new MockRoute(
                Path: "/chat/completions",
                Method: "POST",
                Status: 500,
                Body: "{\"error\":{\"code\":null,\"message\":\"The server had an error while processing your request. Sorry about that!\",\"param\":null,\"type\":\"server_error\"}}",
                StreamChunks: Array.Empty<string>()
            ),
        };

        using var server = new MockServer(routes);
        using var http = new HttpClient();
        http.BaseAddress = new Uri(server.Url);

        var content = new StringContent("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}", System.Text.Encoding.UTF8, "application/json");
        var response = await http.PostAsync("/chat/completions", content);
        Assert.Equal(500, (int)response.StatusCode);
    }
}
