// Code generated by liter-lm-e2e-generator. DO NOT EDIT.

using System.Text.Json;
using System.Net.Http;
using Xunit;

namespace LiterLmE2E;

public sealed class SmokeTests
{

    /// <summary>Basic chat completion with a single user message</summary>
    [Fact]
    public async Task BasicChat()
    {
        var routes = new[]
        {
            new MockRoute(
                Path: "/chat/completions",
                Method: "POST",
                Status: 200,
                Body: "{\"choices\":[{\"finish_reason\":\"stop\",\"index\":0,\"message\":{\"content\":\"Hello!\",\"role\":\"assistant\"}}],\"created\":1711000000,\"id\":\"chatcmpl-abc123\",\"model\":\"gpt-4\",\"object\":\"chat.completion\",\"usage\":{\"completion_tokens\":5,\"prompt_tokens\":10,\"total_tokens\":15}}",
                StreamChunks: Array.Empty<string>()
            ),
        };

        using var server = new MockServer(routes);
        using var http = new HttpClient();
        http.BaseAddress = new Uri(server.Url);

        var content = new StringContent("{\"messages\":[{\"content\":\"Say hello\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"temperature\":0}", System.Text.Encoding.UTF8, "application/json");
        var response = await http.PostAsync("/chat/completions", content);
        response.EnsureSuccessStatusCode();
        var body = await response.Content.ReadAsStringAsync();
        var doc = JsonDocument.Parse(body).RootElement;

        Assert.Equal(1, doc.GetProperty("choices").GetArrayLength());
        Assert.Equal("Hello!", doc.GetProperty("choices")[0].GetProperty("message").GetProperty("content").GetString());
        Assert.Equal("stop", doc.GetProperty("choices")[0].GetProperty("finish_reason").GetString());
        Assert.Equal(15L, doc.GetProperty("usage").GetProperty("total_tokens").GetInt64());
        Assert.Equal("gpt-4", doc.GetProperty("model").GetString());
    }

    /// <summary>Basic embedding request for a single input string</summary>
    [Fact]
    public async Task BasicEmbed()
    {
        var routes = new[]
        {
            new MockRoute(
                Path: "/embeddings",
                Method: "POST",
                Status: 200,
                Body: "{\"data\":[{\"embedding\":[0.1,0.2,0.3,0.4,0.5],\"index\":0,\"object\":\"embedding\"}],\"model\":\"text-embedding-3-small\",\"object\":\"list\",\"usage\":{\"completion_tokens\":0,\"prompt_tokens\":2,\"total_tokens\":2}}",
                StreamChunks: Array.Empty<string>()
            ),
        };

        using var server = new MockServer(routes);
        using var http = new HttpClient();
        http.BaseAddress = new Uri(server.Url);

        var content = new StringContent("{\"input\":\"Hello world\",\"model\":\"text-embedding-3-small\"}", System.Text.Encoding.UTF8, "application/json");
        var response = await http.PostAsync("/embeddings", content);
        response.EnsureSuccessStatusCode();
        var body = await response.Content.ReadAsStringAsync();
        var doc = JsonDocument.Parse(body).RootElement;

        Assert.Equal(1, doc.GetProperty("data").GetArrayLength());
    }

    /// <summary>List available models from the API</summary>
    [Fact]
    public async Task BasicListModels()
    {
        var routes = new[]
        {
            new MockRoute(
                Path: "/models",
                Method: "GET",
                Status: 200,
                Body: "{\"data\":[{\"created\":1687882411,\"id\":\"gpt-4\",\"object\":\"model\",\"owned_by\":\"openai\"},{\"created\":1677610602,\"id\":\"gpt-3.5-turbo\",\"object\":\"model\",\"owned_by\":\"openai\"},{\"created\":1705948997,\"id\":\"text-embedding-3-small\",\"object\":\"model\",\"owned_by\":\"openai\"}],\"object\":\"list\"}",
                StreamChunks: Array.Empty<string>()
            ),
        };

        using var server = new MockServer(routes);
        using var http = new HttpClient();
        http.BaseAddress = new Uri(server.Url);

        var response = await http.GetAsync("/models");
        response.EnsureSuccessStatusCode();
        var body = await response.Content.ReadAsStringAsync();
        var doc = JsonDocument.Parse(body).RootElement;

        Assert.Equal(3, doc.GetProperty("data").GetArrayLength());
    }
}
