// Code generated by liter-lm-e2e-generator. DO NOT EDIT.

using System.Text.Json;
using System.Net.Http;
using Xunit;

namespace LiterLmE2E;

public sealed class StreamingTests
{

    /// <summary>Streaming chat completion that produces content across multiple SSE chunks</summary>
    [Fact]
    public async Task BasicStream()
    {
        var routes = new[]
        {
            new MockRoute(
                Path: "/chat/completions",
                Method: "POST",
                Status: 200,
                Body: "null",
                StreamChunks: new[]
                {
                    "{\"choices\":[{\"delta\":{\"content\":\"\",\"role\":\"assistant\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000000,\"id\":\"chatcmpl-stream001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
                    "{\"choices\":[{\"delta\":{\"content\":\"1\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000000,\"id\":\"chatcmpl-stream001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
                    "{\"choices\":[{\"delta\":{\"content\":\" 2\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000000,\"id\":\"chatcmpl-stream001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
                    "{\"choices\":[{\"delta\":{\"content\":\" 3\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000000,\"id\":\"chatcmpl-stream001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
                    "{\"choices\":[{\"delta\":{},\"finish_reason\":\"stop\",\"index\":0}],\"created\":1711000000,\"id\":\"chatcmpl-stream001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
                }
            ),
        };

        using var server = new MockServer(routes);
        using var http = new HttpClient();
        http.BaseAddress = new Uri(server.Url);

        var content = new StringContent("{\"messages\":[{\"content\":\"Count to 3\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"stream\":true}", System.Text.Encoding.UTF8, "application/json");
        var response = await http.PostAsync("/chat/completions", content);
        response.EnsureSuccessStatusCode();

        var stream = await response.Content.ReadAsStreamAsync();
        using var reader = new System.IO.StreamReader(stream);
        var chunks = new List<string>();
        string? line;
        while ((line = await reader.ReadLineAsync()) != null)
        {
            if (line.StartsWith("data: ") && !line.Contains("[DONE]"))
                chunks.Add(line[6..]);
        }

        Assert.True(chunks.Count >= 3, $"Expected at least 3 chunk(s), got {chunks.Count}");
    }

    /// <summary>Verify that the [DONE] sentinel signal properly terminates the stream</summary>
    [Fact]
    public async Task StreamDoneSignal()
    {
        var routes = new[]
        {
            new MockRoute(
                Path: "/chat/completions",
                Method: "POST",
                Status: 200,
                Body: "null",
                StreamChunks: new[]
                {
                    "{\"choices\":[{\"delta\":{\"content\":\"\",\"role\":\"assistant\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000001,\"id\":\"chatcmpl-done001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
                    "{\"choices\":[{\"delta\":{\"content\":\"Done\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000001,\"id\":\"chatcmpl-done001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
                    "{\"choices\":[{\"delta\":{},\"finish_reason\":\"stop\",\"index\":0}],\"created\":1711000001,\"id\":\"chatcmpl-done001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
                }
            ),
        };

        using var server = new MockServer(routes);
        using var http = new HttpClient();
        http.BaseAddress = new Uri(server.Url);

        var content = new StringContent("{\"messages\":[{\"content\":\"Say done\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"stream\":true}", System.Text.Encoding.UTF8, "application/json");
        var response = await http.PostAsync("/chat/completions", content);
        response.EnsureSuccessStatusCode();

        var stream = await response.Content.ReadAsStreamAsync();
        using var reader = new System.IO.StreamReader(stream);
        var chunks = new List<string>();
        string? line;
        while ((line = await reader.ReadLineAsync()) != null)
        {
            if (line.StartsWith("data: ") && !line.Contains("[DONE]"))
                chunks.Add(line[6..]);
        }

        Assert.True(chunks.Count >= 1, $"Expected at least 1 chunk(s), got {chunks.Count}");
    }
}
