// Code generated by liter-lm-e2e-generator. DO NOT EDIT.

using System.Text.Json;
using System.Net.Http;
using Xunit;

namespace LiterLmE2E;

public sealed class ToolCallingTests
{

    /// <summary>Chat request with a tool definition; assistant responds with a tool call</summary>
    [Fact]
    public async Task SingleToolCall()
    {
        var routes = new[]
        {
            new MockRoute(
                Path: "/chat/completions",
                Method: "POST",
                Status: 200,
                Body: "{\"choices\":[{\"finish_reason\":\"tool_calls\",\"index\":0,\"message\":{\"content\":null,\"role\":\"assistant\",\"tool_calls\":[{\"function\":{\"arguments\":\"{\\\"location\\\": \\\"San Francisco, CA\\\", \\\"unit\\\": \\\"fahrenheit\\\"}\",\"name\":\"get_weather\"},\"id\":\"call_abc123\",\"type\":\"function\"}]}}],\"created\":1711000002,\"id\":\"chatcmpl-tool001\",\"model\":\"gpt-4\",\"object\":\"chat.completion\",\"usage\":{\"completion_tokens\":17,\"prompt_tokens\":82,\"total_tokens\":99}}",
                StreamChunks: Array.Empty<string>()
            ),
        };

        using var server = new MockServer(routes);
        using var http = new HttpClient();
        http.BaseAddress = new Uri(server.Url);

        var content = new StringContent("{\"messages\":[{\"content\":\"What is the weather in San Francisco?\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"tool_choice\":\"auto\",\"tools\":[{\"function\":{\"description\":\"Get the current weather for a given location\",\"name\":\"get_weather\",\"parameters\":{\"properties\":{\"location\":{\"description\":\"The city and state, e.g. San Francisco, CA\",\"type\":\"string\"},\"unit\":{\"description\":\"The temperature unit to use\",\"enum\":[\"celsius\",\"fahrenheit\"],\"type\":\"string\"}},\"required\":[\"location\"],\"type\":\"object\"}},\"type\":\"function\"}]}", System.Text.Encoding.UTF8, "application/json");
        var response = await http.PostAsync("/chat/completions", content);
        response.EnsureSuccessStatusCode();
        var body = await response.Content.ReadAsStringAsync();
        var doc = JsonDocument.Parse(body).RootElement;

        Assert.Equal(1, doc.GetProperty("choices").GetArrayLength());
        Assert.Equal("tool_calls", doc.GetProperty("choices")[0].GetProperty("finish_reason").GetString());
        Assert.Equal(99L, doc.GetProperty("usage").GetProperty("total_tokens").GetInt64());
        Assert.Equal("gpt-4", doc.GetProperty("model").GetString());
    }
}
