// Code generated by liter-lm-e2e-generator. DO NOT EDIT.

import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { startMockServer } from "./helpers.js";
import type { MockServer } from "./helpers.js";

// Note: liter-lm-wasm must be built before running these tests.
// Run `wasm-pack build --target nodejs` in crates/liter-lm-wasm first.
import { LlmClient } from "liter-lm-wasm";


describe("401 Unauthorized error when API key is invalid or missing", () => {
  let server: MockServer;

  beforeAll(async () => {
    server = await startMockServer([{ path: "/chat/completions", method: "POST", status: 401, body: "{\"error\":{\"code\":\"invalid_api_key\",\"message\":\"Incorrect API key provided. You can find your API key at https://platform.openai.com/account/api-keys.\",\"param\":null,\"type\":\"invalid_request_error\"}}", streamChunks: [] }]);
  });

  afterAll(() => {
    server.close();
  });

  it("401 Unauthorized error when API key is invalid or missing", async () => {
    const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url, maxRetries: 0 });

    const req = JSON.parse("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}");
    await expect(client.chat(req)).rejects.toThrow();
  });
});

describe("429 Too Many Requests error when the rate limit is exceeded", () => {
  let server: MockServer;

  beforeAll(async () => {
    server = await startMockServer([{ path: "/chat/completions", method: "POST", status: 429, body: "{\"error\":{\"code\":\"rate_limit_exceeded\",\"message\":\"Rate limit reached for gpt-4 in organization org-abc123 on tokens per min. Limit: 10000, Used: 10000, Requested: 100. Please try again in 600ms.\",\"param\":null,\"type\":\"requests\"}}", streamChunks: [] }]);
  });

  afterAll(() => {
    server.close();
  });

  it("429 Too Many Requests error when the rate limit is exceeded", async () => {
    const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url, maxRetries: 0 });

    const req = JSON.parse("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}");
    await expect(client.chat(req)).rejects.toThrow();
  });
});

describe("500 Internal Server Error from the upstream API", () => {
  let server: MockServer;

  beforeAll(async () => {
    server = await startMockServer([{ path: "/chat/completions", method: "POST", status: 500, body: "{\"error\":{\"code\":null,\"message\":\"The server had an error while processing your request. Sorry about that!\",\"param\":null,\"type\":\"server_error\"}}", streamChunks: [] }]);
  });

  afterAll(() => {
    server.close();
  });

  it("500 Internal Server Error from the upstream API", async () => {
    const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url, maxRetries: 0 });

    const req = JSON.parse("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}");
    await expect(client.chat(req)).rejects.toThrow();
  });
});
