// Code generated by liter-lm-e2e-generator. DO NOT EDIT.

import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { startMockServer } from "./helpers.js";
import type { MockServer } from "./helpers.js";

// Note: liter-lm-wasm must be built before running these tests.
// Run `wasm-pack build --target nodejs` in crates/liter-lm-wasm first.
import { LlmClient } from "liter-lm-wasm";


describe("Basic chat completion with a single user message", () => {
  let server: MockServer;

  beforeAll(async () => {
    server = await startMockServer([{ path: "/chat/completions", method: "POST", status: 200, body: "{\"choices\":[{\"finish_reason\":\"stop\",\"index\":0,\"message\":{\"content\":\"Hello!\",\"role\":\"assistant\"}}],\"created\":1711000000,\"id\":\"chatcmpl-abc123\",\"model\":\"gpt-4\",\"object\":\"chat.completion\",\"usage\":{\"completion_tokens\":5,\"prompt_tokens\":10,\"total_tokens\":15}}", streamChunks: [] }]);
  });

  afterAll(() => {
    server.close();
  });

  it("Basic chat completion with a single user message", async () => {
    const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url, maxRetries: 0 });

    const req = JSON.parse("{\"messages\":[{\"content\":\"Say hello\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"temperature\":0}");
    const response = await client.chat(req);
    expect((response as { choices: unknown[] }).choices).toHaveLength(1);
    expect((response as { choices: { message: { content: string } }[] }).choices[0].message.content).toBe("Hello!");
    expect((response as { model: string }).model).toBe("gpt-4");
  });
});

describe("Basic embedding request for a single input string", () => {
  let server: MockServer;

  beforeAll(async () => {
    server = await startMockServer([{ path: "/embeddings", method: "POST", status: 200, body: "{\"data\":[{\"embedding\":[0.1,0.2,0.3,0.4,0.5],\"index\":0,\"object\":\"embedding\"}],\"model\":\"text-embedding-3-small\",\"object\":\"list\",\"usage\":{\"completion_tokens\":0,\"prompt_tokens\":2,\"total_tokens\":2}}", streamChunks: [] }]);
  });

  afterAll(() => {
    server.close();
  });

  it("Basic embedding request for a single input string", async () => {
    const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url, maxRetries: 0 });

    const req = JSON.parse("{\"input\":\"Hello world\",\"model\":\"text-embedding-3-small\"}");
    const response = await client.embed(req);
    expect((response as { data: unknown[] }).data).toHaveLength(1);
  });
});

describe("List available models from the API", () => {
  let server: MockServer;

  beforeAll(async () => {
    server = await startMockServer([{ path: "/models", method: "GET", status: 200, body: "{\"data\":[{\"created\":1687882411,\"id\":\"gpt-4\",\"object\":\"model\",\"owned_by\":\"openai\"},{\"created\":1677610602,\"id\":\"gpt-3.5-turbo\",\"object\":\"model\",\"owned_by\":\"openai\"},{\"created\":1705948997,\"id\":\"text-embedding-3-small\",\"object\":\"model\",\"owned_by\":\"openai\"}],\"object\":\"list\"}", streamChunks: [] }]);
  });

  afterAll(() => {
    server.close();
  });

  it("List available models from the API", async () => {
    const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url, maxRetries: 0 });

    const response = await client.listModels();
    expect((response as { data: unknown[] }).data).toHaveLength(3);
  });
});
