// Code generated by liter-lm-e2e-generator. DO NOT EDIT.

import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { startMockServer } from "./helpers.js";
import type { MockServer } from "./helpers.js";

// Note: liter-lm-wasm must be built before running these tests.
// Run `wasm-pack build --target nodejs` in crates/liter-lm-wasm first.
import { LlmClient } from "liter-lm-wasm";


describe("Streaming chat completion that produces content across multiple SSE chunks", () => {
  let server: MockServer;

  beforeAll(async () => {
    server = await startMockServer([{
      path: "/chat/completions",
      method: "POST",
      status: 200,
      body: "null",
      streamChunks: [
        "{\"choices\":[{\"delta\":{\"content\":\"\",\"role\":\"assistant\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000000,\"id\":\"chatcmpl-stream001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
        "{\"choices\":[{\"delta\":{\"content\":\"1\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000000,\"id\":\"chatcmpl-stream001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
        "{\"choices\":[{\"delta\":{\"content\":\" 2\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000000,\"id\":\"chatcmpl-stream001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
        "{\"choices\":[{\"delta\":{\"content\":\" 3\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000000,\"id\":\"chatcmpl-stream001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
        "{\"choices\":[{\"delta\":{},\"finish_reason\":\"stop\",\"index\":0}],\"created\":1711000000,\"id\":\"chatcmpl-stream001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
      ],
    }]);
  });

  afterAll(() => {
    server.close();
  });

  it("Streaming chat completion that produces content across multiple SSE chunks", async () => {
    const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url, maxRetries: 0 });

    const req = JSON.parse("{\"messages\":[{\"content\":\"Count to 3\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"stream\":true}");
    const chunks: unknown[] = [];
    for await (const chunk of client.chatStream(req)) {
      chunks.push(chunk);
    }

    expect(chunks.length).toBeGreaterThanOrEqual(3);
  });
});

describe("Verify that the [DONE] sentinel signal properly terminates the stream", () => {
  let server: MockServer;

  beforeAll(async () => {
    server = await startMockServer([{
      path: "/chat/completions",
      method: "POST",
      status: 200,
      body: "null",
      streamChunks: [
        "{\"choices\":[{\"delta\":{\"content\":\"\",\"role\":\"assistant\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000001,\"id\":\"chatcmpl-done001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
        "{\"choices\":[{\"delta\":{\"content\":\"Done\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000001,\"id\":\"chatcmpl-done001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
        "{\"choices\":[{\"delta\":{},\"finish_reason\":\"stop\",\"index\":0}],\"created\":1711000001,\"id\":\"chatcmpl-done001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
      ],
    }]);
  });

  afterAll(() => {
    server.close();
  });

  it("Verify that the [DONE] sentinel signal properly terminates the stream", async () => {
    const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url, maxRetries: 0 });

    const req = JSON.parse("{\"messages\":[{\"content\":\"Say done\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"stream\":true}");
    const chunks: unknown[] = [];
    for await (const chunk of client.chatStream(req)) {
      chunks.push(chunk);
    }

    expect(chunks.length).toBeGreaterThanOrEqual(1);
  });
});
