# Code generated by liter-lm-e2e-generator. DO NOT EDIT.
# frozen_string_literal: true

require "spec_helper"

RSpec.describe "error-handling" do
  it "auth_401" do
    # 401 Unauthorized error when API key is invalid or missing
    route = E2EHelpers::MockRoute.new(
      path: "/chat/completions",
      method: "POST",
      status: 401,
      body: '{"error":{"code":"invalid_api_key","message":"Incorrect API key provided. You can find your API key at https://platform.openai.com/account/api-keys.","param":null,"type":"invalid_request_error"}}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    response = post_json(server.url, "/chat/completions", '{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}')

    expect(response.code.to_i).to eq(401)
    expect(response.code.to_i).to be >= 400

  ensure
    server&.stop
  end

  it "rate_limit_429" do
    # 429 Too Many Requests error when the rate limit is exceeded
    route = E2EHelpers::MockRoute.new(
      path: "/chat/completions",
      method: "POST",
      status: 429,
      body: '{"error":{"code":"rate_limit_exceeded","message":"Rate limit reached for gpt-4 in organization org-abc123 on tokens per min. Limit: 10000, Used: 10000, Requested: 100. Please try again in 600ms.","param":null,"type":"requests"}}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    response = post_json(server.url, "/chat/completions", '{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}')

    expect(response.code.to_i).to eq(429)
    expect(response.code.to_i).to be >= 400

  ensure
    server&.stop
  end

  it "server_error_500" do
    # 500 Internal Server Error from the upstream API
    route = E2EHelpers::MockRoute.new(
      path: "/chat/completions",
      method: "POST",
      status: 500,
      body: '{"error":{"code":null,"message":"The server had an error while processing your request. Sorry about that!","param":null,"type":"server_error"}}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    response = post_json(server.url, "/chat/completions", '{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}')

    expect(response.code.to_i).to eq(500)
    expect(response.code.to_i).to be >= 400

  ensure
    server&.stop
  end

end
