# Code generated by liter-lm-e2e-generator. DO NOT EDIT.
# frozen_string_literal: true

require "spec_helper"

RSpec.describe "smoke" do
  it "basic_chat" do
    # Basic chat completion with a single user message
    route = E2EHelpers::MockRoute.new(
      path: "/chat/completions",
      method: "POST",
      status: 200,
      body: '{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hello!","role":"assistant"}}],"created":1711000000,"id":"chatcmpl-abc123","model":"gpt-4","object":"chat.completion","usage":{"completion_tokens":5,"prompt_tokens":10,"total_tokens":15}}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    response = post_json(server.url, "/chat/completions", '{"messages":[{"content":"Say hello","role":"user"}],"model":"gpt-4","temperature":0}')

    expect(response.code.to_i).to eq(200)

    body = JSON.parse(response.body)

    expect(body["choices"].size).to eq(1)
    expect(body.dig("choices", 0, "message", "content")).to eq('Hello!')
    expect(body.dig("choices", 0, "finish_reason")).to eq('stop')
    expect(body["model"]).to eq('gpt-4')
    expect(body["usage"]).not_to be_nil
    expect(body.dig("usage", "total_tokens")).to eq(15)

  ensure
    server&.stop
  end

  it "basic_embed" do
    # Basic embedding request for a single input string
    route = E2EHelpers::MockRoute.new(
      path: "/embeddings",
      method: "POST",
      status: 200,
      body: '{"data":[{"embedding":[0.1,0.2,0.3,0.4,0.5],"index":0,"object":"embedding"}],"model":"text-embedding-3-small","object":"list","usage":{"completion_tokens":0,"prompt_tokens":2,"total_tokens":2}}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    response = post_json(server.url, "/embeddings", '{"input":"Hello world","model":"text-embedding-3-small"}')

    expect(response.code.to_i).to eq(200)

    body = JSON.parse(response.body)
    expect(body["data"].size).to eq(1)

  ensure
    server&.stop
  end

  it "basic_list_models" do
    # List available models from the API
    route = E2EHelpers::MockRoute.new(
      path: "/models",
      method: "GET",
      status: 200,
      body: '{"data":[{"created":1687882411,"id":"gpt-4","object":"model","owned_by":"openai"},{"created":1677610602,"id":"gpt-3.5-turbo","object":"model","owned_by":"openai"},{"created":1705948997,"id":"text-embedding-3-small","object":"model","owned_by":"openai"}],"object":"list"}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    response = get_json(server.url, "/models")

    expect(response.code.to_i).to eq(200)

    body = JSON.parse(response.body)
    expect(body["data"].size).to eq(3)

  ensure
    server&.stop
  end

end
