# Code generated by liter-lm-e2e-generator. DO NOT EDIT.
# frozen_string_literal: true

require "spec_helper"

RSpec.describe "tool-calling" do
  it "single_tool_call" do
    # Chat request with a tool definition; assistant responds with a tool call
    route = E2EHelpers::MockRoute.new(
      path: "/chat/completions",
      method: "POST",
      status: 200,
      body: "{\"choices\":[{\"finish_reason\":\"tool_calls\",\"index\":0,\"message\":{\"content\":null,\"role\":\"assistant\",\"tool_calls\":[{\"function\":{\"arguments\":\"{\\\"location\\\": \\\"San Francisco, CA\\\", \\\"unit\\\": \\\"fahrenheit\\\"}\",\"name\":\"get_weather\"},\"id\":\"call_abc123\",\"type\":\"function\"}]}}],\"created\":1711000002,\"id\":\"chatcmpl-tool001\",\"model\":\"gpt-4\",\"object\":\"chat.completion\",\"usage\":{\"completion_tokens\":17,\"prompt_tokens\":82,\"total_tokens\":99}}",
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    response = post_json(server.url, "/chat/completions", '{"messages":[{"content":"What is the weather in San Francisco?","role":"user"}],"model":"gpt-4","tool_choice":"auto","tools":[{"function":{"description":"Get the current weather for a given location","name":"get_weather","parameters":{"properties":{"location":{"description":"The city and state, e.g. San Francisco, CA","type":"string"},"unit":{"description":"The temperature unit to use","enum":["celsius","fahrenheit"],"type":"string"}},"required":["location"],"type":"object"}},"type":"function"}]}')

    expect(response.code.to_i).to eq(200)

    body = JSON.parse(response.body)

    expect(body["choices"].size).to eq(1)
    expect(body.dig("choices", 0, "finish_reason")).to eq('tool_calls')
    expect(body["model"]).to eq('gpt-4')
    expect(body["usage"]).not_to be_nil
    expect(body.dig("usage", "total_tokens")).to eq(99)

  ensure
    server&.stop
  end

end
