/* Code generated by liter-lm-e2e-generator. DO NOT EDIT. */

#include "helpers.h"

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* 401 Unauthorized error when API key is invalid or missing */
static void test_auth_401(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"error\":{\"code\":\"invalid_api_key\",\"message\":\"Incorrect API "
      "key provided. You can find your API key at "
      "https://platform.openai.com/account/"
      "api-keys.\",\"param\":null,\"type\":\"invalid_request_error\"}}";

  const char *base_url = getenv("LITER_LM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/chat/completions", base_url);

    LiterLmResponse *resp =
        liter_lm_http_post(url, "{\"messages\":[{\"content\":\"Hello\","
                                "\"role\":\"user\"}],\"model\":\"gpt-4\"}");
    assert(resp != NULL);
    liter_lm_assert_status(resp, 401L, "test_auth_401");
    liter_lm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    (void)mock_body; /* error or stream test — skip offline assertions */
  }
}

/* 429 Too Many Requests error when the rate limit is exceeded */
static void test_rate_limit_429(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"error\":{\"code\":\"rate_limit_exceeded\",\"message\":\"Rate limit "
      "reached for gpt-4 in organization org-abc123 on tokens per min. Limit: "
      "10000, Used: 10000, Requested: 100. Please try again in "
      "600ms.\",\"param\":null,\"type\":\"requests\"}}";

  const char *base_url = getenv("LITER_LM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/chat/completions", base_url);

    LiterLmResponse *resp =
        liter_lm_http_post(url, "{\"messages\":[{\"content\":\"Hello\","
                                "\"role\":\"user\"}],\"model\":\"gpt-4\"}");
    assert(resp != NULL);
    liter_lm_assert_status(resp, 429L, "test_rate_limit_429");
    liter_lm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    (void)mock_body; /* error or stream test — skip offline assertions */
  }
}

/* 500 Internal Server Error from the upstream API */
static void test_server_error_500(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"error\":{\"code\":null,\"message\":\"The server had an error while "
      "processing your request. Sorry about "
      "that!\",\"param\":null,\"type\":\"server_error\"}}";

  const char *base_url = getenv("LITER_LM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/chat/completions", base_url);

    LiterLmResponse *resp =
        liter_lm_http_post(url, "{\"messages\":[{\"content\":\"Hello\","
                                "\"role\":\"user\"}],\"model\":\"gpt-4\"}");
    assert(resp != NULL);
    liter_lm_assert_status(resp, 500L, "test_server_error_500");
    liter_lm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    (void)mock_body; /* error or stream test — skip offline assertions */
  }
}

int main(void) {
  test_auth_401();
  printf("PASS: 401 Unauthorized error when API key is invalid or missing\n");
  test_rate_limit_429();
  printf("PASS: 429 Too Many Requests error when the rate limit is exceeded\n");
  test_server_error_500();
  printf("PASS: 500 Internal Server Error from the upstream API\n");
  printf("All error_handling tests passed.\n");
  return 0;
}
