/* Code generated by liter-lm-e2e-generator. DO NOT EDIT. */

#include "helpers.h"

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Chat request with a tool definition; assistant responds with a tool call */
static void test_single_tool_call(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"choices\":[{\"finish_reason\":\"tool_calls\",\"index\":0,\"message\":"
      "{\"content\":null,\"role\":\"assistant\",\"tool_calls\":[{\"function\":{"
      "\"arguments\":\"{\\\"location\\\": \\\"San Francisco, CA\\\", "
      "\\\"unit\\\": "
      "\\\"fahrenheit\\\"}\",\"name\":\"get_weather\"},\"id\":\"call_abc123\","
      "\"type\":\"function\"}]}}],\"created\":1711000002,\"id\":\"chatcmpl-"
      "tool001\",\"model\":\"gpt-4\",\"object\":\"chat.completion\",\"usage\":{"
      "\"completion_tokens\":17,\"prompt_tokens\":82,\"total_tokens\":99}}";

  const char *base_url = getenv("LITER_LM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/chat/completions", base_url);

    LiterLmResponse *resp = liter_lm_http_post(
        url,
        "{\"messages\":[{\"content\":\"What is the weather in San "
        "Francisco?\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"tool_choice\":"
        "\"auto\",\"tools\":[{\"function\":{\"description\":\"Get the current "
        "weather for a given "
        "location\",\"name\":\"get_weather\",\"parameters\":{\"properties\":{"
        "\"location\":{\"description\":\"The city and state, e.g. San "
        "Francisco, CA\",\"type\":\"string\"},\"unit\":{\"description\":\"The "
        "temperature unit to "
        "use\",\"enum\":[\"celsius\",\"fahrenheit\"],\"type\":\"string\"}},"
        "\"required\":[\"location\"],\"type\":\"object\"}},\"type\":"
        "\"function\"}]}");
    assert(resp != NULL);
    liter_lm_assert_status(resp, 200L, "test_single_tool_call");
    liter_lm_assert_json_array_len(resp->body, "choices", 1,
                                   "test_single_tool_call");
    liter_lm_assert_json_field(resp->body, "model", "gpt-4",
                               "test_single_tool_call");
    liter_lm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    liter_lm_assert_json_array_len(mock_body, "choices", 1,
                                   "test_single_tool_call");
    liter_lm_assert_json_field(mock_body, "model", "gpt-4",
                               "test_single_tool_call");
  }
}

int main(void) {
  test_single_tool_call();
  printf("PASS: Chat request with a tool definition; assistant responds with a "
         "tool call\n");
  printf("All tool_calling tests passed.\n");
  return 0;
}
