/* Code generated by liter-lm-e2e-generator. DO NOT EDIT. */

#include "helpers.h"

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Basic chat completion with a single user message */
static void test_basic_chat(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"choices\":[{\"finish_reason\":\"stop\",\"index\":0,\"message\":{"
      "\"content\":\"Hello!\",\"role\":\"assistant\"}}],\"created\":1711000000,"
      "\"id\":\"chatcmpl-abc123\",\"model\":\"gpt-4\",\"object\":\"chat."
      "completion\",\"usage\":{\"completion_tokens\":5,\"prompt_tokens\":10,"
      "\"total_tokens\":15}}";

  const char *base_url = getenv("LITER_LM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/chat/completions", base_url);

    LiterLmResponse *resp = liter_lm_http_post(
        url,
        "{\"messages\":[{\"content\":\"Say "
        "hello\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"temperature\":0}");
    assert(resp != NULL);
    liter_lm_assert_status(resp, 200L, "test_basic_chat");
    liter_lm_assert_json_array_len(resp->body, "choices", 1, "test_basic_chat");
    liter_lm_assert_json_field(resp->body, "content", "Hello!",
                               "test_basic_chat");
    liter_lm_assert_json_field(resp->body, "model", "gpt-4", "test_basic_chat");
    liter_lm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    liter_lm_assert_json_array_len(mock_body, "choices", 1, "test_basic_chat");
    liter_lm_assert_json_field(mock_body, "content", "Hello!",
                               "test_basic_chat");
    liter_lm_assert_json_field(mock_body, "model", "gpt-4", "test_basic_chat");
  }
}

/* Basic embedding request for a single input string */
static void test_basic_embed(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"data\":[{\"embedding\":[0.1,0.2,0.3,0.4,0.5],\"index\":0,\"object\":"
      "\"embedding\"}],\"model\":\"text-embedding-3-small\",\"object\":"
      "\"list\",\"usage\":{\"completion_tokens\":0,\"prompt_tokens\":2,\"total_"
      "tokens\":2}}";

  const char *base_url = getenv("LITER_LM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/embeddings", base_url);

    LiterLmResponse *resp = liter_lm_http_post(
        url,
        "{\"input\":\"Hello world\",\"model\":\"text-embedding-3-small\"}");
    assert(resp != NULL);
    liter_lm_assert_status(resp, 200L, "test_basic_embed");
    liter_lm_assert_json_array_len(resp->body, "data", 1, "test_basic_embed");
    liter_lm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    liter_lm_assert_json_array_len(mock_body, "data", 1, "test_basic_embed");
  }
}

/* List available models from the API */
static void test_basic_list_models(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"data\":[{\"created\":1687882411,\"id\":\"gpt-4\",\"object\":"
      "\"model\",\"owned_by\":\"openai\"},{\"created\":1677610602,\"id\":\"gpt-"
      "3.5-turbo\",\"object\":\"model\",\"owned_by\":\"openai\"},{\"created\":"
      "1705948997,\"id\":\"text-embedding-3-small\",\"object\":\"model\","
      "\"owned_by\":\"openai\"}],\"object\":\"list\"}";

  const char *base_url = getenv("LITER_LM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/models", base_url);

    LiterLmResponse *resp = liter_lm_http_get(url);
    assert(resp != NULL);
    liter_lm_assert_status(resp, 200L, "test_basic_list_models");
    liter_lm_assert_json_array_len(resp->body, "data", 3,
                                   "test_basic_list_models");
    liter_lm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    liter_lm_assert_json_array_len(mock_body, "data", 3,
                                   "test_basic_list_models");
  }
}

int main(void) {
  test_basic_chat();
  printf("PASS: Basic chat completion with a single user message\n");
  test_basic_embed();
  printf("PASS: Basic embedding request for a single input string\n");
  test_basic_list_models();
  printf("PASS: List available models from the API\n");
  printf("All smoke tests passed.\n");
  return 0;
}
