/* Code generated by liter-lm-e2e-generator. DO NOT EDIT. */

#include "helpers.h"

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Streaming chat completion that produces content across multiple SSE chunks */
static void test_basic_stream(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body = "null";

  const char *base_url = getenv("LITER_LM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/chat/completions", base_url);

    char *chunks[256];
    int n = liter_lm_read_sse(
        url,
        "{\"messages\":[{\"content\":\"Count to "
        "3\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"stream\":true}",
        chunks, 256);
    if (n < 3) {
      fprintf(stderr,
              "FAIL [test_basic_stream]: expected >= 3 chunks, got %d\n", n);
      abort();
    }
    for (int i = 0; i < n; i++)
      free(chunks[i]);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    (void)mock_body; /* error or stream test — skip offline assertions */
  }
}

/* Verify that the [DONE] sentinel signal properly terminates the stream */
static void test_stream_done_signal(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body = "null";

  const char *base_url = getenv("LITER_LM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/chat/completions", base_url);

    char *chunks[256];
    int n = liter_lm_read_sse(
        url,
        "{\"messages\":[{\"content\":\"Say "
        "done\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"stream\":true}",
        chunks, 256);
    if (n < 1) {
      fprintf(stderr,
              "FAIL [test_stream_done_signal]: expected >= 1 chunks, got %d\n",
              n);
      abort();
    }
    for (int i = 0; i < n; i++)
      free(chunks[i]);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    (void)mock_body; /* error or stream test — skip offline assertions */
  }
}

int main(void) {
  test_basic_stream();
  printf("PASS: Streaming chat completion that produces content across "
         "multiple SSE chunks\n");
  test_stream_done_signal();
  printf("PASS: Verify that the [DONE] sentinel signal properly terminates the "
         "stream\n");
  printf("All streaming tests passed.\n");
  return 0;
}
