// Code generated by liter-lm-e2e-generator. DO NOT EDIT.

package literlm_e2e

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"testing"
)

func TestErrorHandling(t *testing.T) {
	t.Run("auth_401", func(t *testing.T) {
		// 401 Unauthorized error when API key is invalid or missing
		server := NewMockServer([]MockRoute{
			{
				Path:         "/chat/completions",
				Method:       "POST",
				Status:       401,
				Body:         `{"error":{"code":"invalid_api_key","message":"Incorrect API key provided. You can find your API key at https://platform.openai.com/account/api-keys.","param":null,"type":"invalid_request_error"}}`,
				StreamChunks: nil,
			},
		})
		defer server.Close()

		reqBody := bytes.NewBufferString("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
		resp, err := http.Post(server.URL+"/chat/completions", "application/json", reqBody)
		if err != nil {
			t.Fatalf("http.Post failed: %v", err)
		}
		defer resp.Body.Close()

		AssertTrue(t, "expected error status", resp.StatusCode >= 400)
		AssertEqual(t, "error status code", 401, resp.StatusCode)
		_ = fmt.Sprintf("") // suppress import
	})

	t.Run("rate_limit_429", func(t *testing.T) {
		// 429 Too Many Requests error when the rate limit is exceeded
		server := NewMockServer([]MockRoute{
			{
				Path:         "/chat/completions",
				Method:       "POST",
				Status:       429,
				Body:         `{"error":{"code":"rate_limit_exceeded","message":"Rate limit reached for gpt-4 in organization org-abc123 on tokens per min. Limit: 10000, Used: 10000, Requested: 100. Please try again in 600ms.","param":null,"type":"requests"}}`,
				StreamChunks: nil,
			},
		})
		defer server.Close()

		reqBody := bytes.NewBufferString("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
		resp, err := http.Post(server.URL+"/chat/completions", "application/json", reqBody)
		if err != nil {
			t.Fatalf("http.Post failed: %v", err)
		}
		defer resp.Body.Close()

		AssertTrue(t, "expected error status", resp.StatusCode >= 400)
		AssertEqual(t, "error status code", 429, resp.StatusCode)
		_ = fmt.Sprintf("") // suppress import
	})

	t.Run("server_error_500", func(t *testing.T) {
		// 500 Internal Server Error from the upstream API
		server := NewMockServer([]MockRoute{
			{
				Path:         "/chat/completions",
				Method:       "POST",
				Status:       500,
				Body:         `{"error":{"code":null,"message":"The server had an error while processing your request. Sorry about that!","param":null,"type":"server_error"}}`,
				StreamChunks: nil,
			},
		})
		defer server.Close()

		reqBody := bytes.NewBufferString("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
		resp, err := http.Post(server.URL+"/chat/completions", "application/json", reqBody)
		if err != nil {
			t.Fatalf("http.Post failed: %v", err)
		}
		defer resp.Body.Close()

		AssertTrue(t, "expected error status", resp.StatusCode >= 400)
		AssertEqual(t, "error status code", 500, resp.StatusCode)
		_ = fmt.Sprintf("") // suppress import
	})

}
